// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.alicloud.vpc;

import com.pulumi.alicloud.Utilities;
import com.pulumi.alicloud.vpc.RouteEntryArgs;
import com.pulumi.alicloud.vpc.inputs.RouteEntryState;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Provides a route entry resource. A route entry represents a route item of one VPC route table.
 * 
 * ## Example Usage
 * 
 * Basic Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Module Support
 * 
 * You can use to the existing vpc module
 * to create a VPC, several VSwitches and add several route entries one-click.
 * 
 * ## Import
 * 
 * Router entry can be imported using the id, e.g (formatted as&lt;route_table_id:router_id:destination_cidrblock:nexthop_type:nexthop_id&gt;).
 * 
 * ```sh
 * $ pulumi import alicloud:vpc/routeEntry:RouteEntry example vtb-123456:vrt-123456:0.0.0.0/0:NatGateway:ngw-123456
 * ```
 * 
 */
@ResourceType(type="alicloud:vpc/routeEntry:RouteEntry")
public class RouteEntry extends com.pulumi.resources.CustomResource {
    /**
     * The RouteEntry&#39;s target network segment.
     * 
     */
    @Export(name="destinationCidrblock", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> destinationCidrblock;

    /**
     * @return The RouteEntry&#39;s target network segment.
     * 
     */
    public Output<Optional<String>> destinationCidrblock() {
        return Codegen.optional(this.destinationCidrblock);
    }
    /**
     * The name of the route entry. This name can have a string of 2 to 128 characters, must contain only alphanumeric characters or hyphens, such as &#34;-&#34;,&#34;.&#34;,&#34;_&#34;, and must not begin or end with a hyphen, and must not begin with http:// or https://.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name of the route entry. This name can have a string of 2 to 128 characters, must contain only alphanumeric characters or hyphens, such as &#34;-&#34;,&#34;.&#34;,&#34;_&#34;, and must not begin or end with a hyphen, and must not begin with http:// or https://.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The route entry&#39;s next hop. ECS instance ID or VPC router interface ID.
     * 
     */
    @Export(name="nexthopId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> nexthopId;

    /**
     * @return The route entry&#39;s next hop. ECS instance ID or VPC router interface ID.
     * 
     */
    public Output<Optional<String>> nexthopId() {
        return Codegen.optional(this.nexthopId);
    }
    /**
     * The next hop type. Available values:
     * - `Instance` (Default): an Elastic Compute Service (ECS) instance. This is the default value.
     * - `RouterInterface`: a router interface.
     * - `VpnGateway`: a VPN Gateway.
     * - `HaVip`: a high-availability virtual IP address (HAVIP).
     * - `NetworkInterface`: an elastic network interface (ENI).
     * - `NatGateway`: a Nat Gateway.
     * - `IPv6Gateway`: an IPv6 gateway.
     * - `Attachment`: a transit router.
     * - `VpcPeer`: a VPC Peering Connection.
     * - `Ipv4Gateway`  (Available in 1.193.0+): an IPv4 gateway.
     * 
     */
    @Export(name="nexthopType", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> nexthopType;

    /**
     * @return The next hop type. Available values:
     * - `Instance` (Default): an Elastic Compute Service (ECS) instance. This is the default value.
     * - `RouterInterface`: a router interface.
     * - `VpnGateway`: a VPN Gateway.
     * - `HaVip`: a high-availability virtual IP address (HAVIP).
     * - `NetworkInterface`: an elastic network interface (ENI).
     * - `NatGateway`: a Nat Gateway.
     * - `IPv6Gateway`: an IPv6 gateway.
     * - `Attachment`: a transit router.
     * - `VpcPeer`: a VPC Peering Connection.
     * - `Ipv4Gateway`  (Available in 1.193.0+): an IPv4 gateway.
     * 
     */
    public Output<Optional<String>> nexthopType() {
        return Codegen.optional(this.nexthopType);
    }
    /**
     * The ID of the route table.
     * 
     */
    @Export(name="routeTableId", refs={String.class}, tree="[0]")
    private Output<String> routeTableId;

    /**
     * @return The ID of the route table.
     * 
     */
    public Output<String> routeTableId() {
        return this.routeTableId;
    }
    /**
     * This argument has been deprecated. Please use other arguments to launch a custom route entry.
     * 
     * @deprecated
     * Attribute router_id has been deprecated and suggest removing it from your template.
     * 
     */
    @Deprecated /* Attribute router_id has been deprecated and suggest removing it from your template. */
    @Export(name="routerId", refs={String.class}, tree="[0]")
    private Output<String> routerId;

    /**
     * @return This argument has been deprecated. Please use other arguments to launch a custom route entry.
     * 
     */
    public Output<String> routerId() {
        return this.routerId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public RouteEntry(java.lang.String name) {
        this(name, RouteEntryArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public RouteEntry(java.lang.String name, RouteEntryArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public RouteEntry(java.lang.String name, RouteEntryArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("alicloud:vpc/routeEntry:RouteEntry", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private RouteEntry(java.lang.String name, Output<java.lang.String> id, @Nullable RouteEntryState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("alicloud:vpc/routeEntry:RouteEntry", name, state, makeResourceOptions(options, id), false);
    }

    private static RouteEntryArgs makeArgs(RouteEntryArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? RouteEntryArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static RouteEntry get(java.lang.String name, Output<java.lang.String> id, @Nullable RouteEntryState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new RouteEntry(name, id, state, options);
    }
}
