// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AliCloud.Ecs
{
    /// <summary>
    /// Provides a Security Group Rule resource.
    /// 
    /// For information about Security Group Rule and how to use it, see [What is Rule](https://www.alibabacloud.com/help/en/ecs/user-guide/security-group-rules).
    /// 
    /// &gt; **NOTE:** Available since v0.1.0.
    /// 
    /// Represents a single `ingress` or `egress` group rule, which can be added to external Security Groups.
    /// 
    /// &gt; **NOTE:**  `nic_type` should set to `intranet` when security group type is `vpc` or specifying the `source_security_group_id`. In this situation it does not distinguish between intranet and internet, the rule is effective on them both.
    /// 
    /// ## Import
    /// 
    /// Security Group Rule can be imported using the id, e.g.
    /// 
    /// ```sh
    /// $ pulumi import alicloud:ecs/securityGroupRule:SecurityGroupRule example &lt;id&gt;
    /// ```
    /// </summary>
    [AliCloudResourceType("alicloud:ecs/securityGroupRule:SecurityGroupRule")]
    public partial class SecurityGroupRule : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The description of the security group rule. The description can be up to 1 to 512 characters in length. Defaults to null.
        /// 
        /// &gt; **NOTE:**  You must specify one of the following field: `cidr_ip`,`source_security_group_id`,`prefix_list_id`,`ipv6_cidr_ip`.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        [Output("destCidrIp")]
        public Output<string?> DestCidrIp { get; private set; } = null!;

        [Output("destGroupId")]
        public Output<string?> DestGroupId { get; private set; } = null!;

        [Output("destGroupOwnerAccount")]
        public Output<string?> DestGroupOwnerAccount { get; private set; } = null!;

        [Output("destPrefixListId")]
        public Output<string> DestPrefixListId { get; private set; } = null!;

        /// <summary>
        /// The transport layer protocol of the Security Group Rule. Valid values: `tcp`, `udp`, `icmp`, `gre`, `all`.
        /// </summary>
        [Output("ipProtocol")]
        public Output<string> IpProtocol { get; private set; } = null!;

        [Output("ipv6DestCidrIp")]
        public Output<string?> Ipv6DestCidrIp { get; private set; } = null!;

        [Output("ipv6SourceCidrIp")]
        public Output<string?> Ipv6SourceCidrIp { get; private set; } = null!;

        /// <summary>
        /// Network type, can be either `internet` or `intranet`, the default value is `internet`.
        /// </summary>
        [Output("nicType")]
        public Output<string> NicType { get; private set; } = null!;

        /// <summary>
        /// The action of the Security Group Rule that determines whether to allow inbound access. Default value: `accept`. Valid values: `accept`, `drop`.
        /// </summary>
        [Output("policy")]
        public Output<string?> Policy { get; private set; } = null!;

        /// <summary>
        /// The range of port numbers relevant to the IP protocol. Default to "-1/-1". When the protocol is tcp or udp, each side port number range from 1 to 65535 and '-1/-1' will be invalid.
        /// For example, `1/200` means that the range of the port numbers is 1-200. Other protocols' 'port_range' can only be "-1/-1", and other values will be invalid.
        /// </summary>
        [Output("portRange")]
        public Output<string?> PortRange { get; private set; } = null!;

        /// <summary>
        /// The priority of the Security Group Rule. Default value: `1`. Valid values: `1` to `100`.
        /// </summary>
        [Output("priority")]
        public Output<int?> Priority { get; private set; } = null!;

        /// <summary>
        /// The ID of the Security Group.
        /// </summary>
        [Output("securityGroupId")]
        public Output<string> SecurityGroupId { get; private set; } = null!;

        [Output("sourceCidrIp")]
        public Output<string?> SourceCidrIp { get; private set; } = null!;

        [Output("sourceGroupId")]
        public Output<string?> SourceGroupId { get; private set; } = null!;

        /// <summary>
        /// The Alibaba Cloud user account Id of the target security group when security groups are authorized across accounts.  This parameter is invalid if `cidr_ip` has already been set.
        /// </summary>
        [Output("sourceGroupOwnerAccount")]
        public Output<string?> SourceGroupOwnerAccount { get; private set; } = null!;

        [Output("sourcePortRange")]
        public Output<string?> SourcePortRange { get; private set; } = null!;

        [Output("sourcePrefixListId")]
        public Output<string> SourcePrefixListId { get; private set; } = null!;

        /// <summary>
        /// The type of the Security Group Rule. Valid values:
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;


        /// <summary>
        /// Create a SecurityGroupRule resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SecurityGroupRule(string name, SecurityGroupRuleArgs args, CustomResourceOptions? options = null)
            : base("alicloud:ecs/securityGroupRule:SecurityGroupRule", name, args ?? new SecurityGroupRuleArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SecurityGroupRule(string name, Input<string> id, SecurityGroupRuleState? state = null, CustomResourceOptions? options = null)
            : base("alicloud:ecs/securityGroupRule:SecurityGroupRule", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SecurityGroupRule resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SecurityGroupRule Get(string name, Input<string> id, SecurityGroupRuleState? state = null, CustomResourceOptions? options = null)
        {
            return new SecurityGroupRule(name, id, state, options);
        }
    }

    public sealed class SecurityGroupRuleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The description of the security group rule. The description can be up to 1 to 512 characters in length. Defaults to null.
        /// 
        /// &gt; **NOTE:**  You must specify one of the following field: `cidr_ip`,`source_security_group_id`,`prefix_list_id`,`ipv6_cidr_ip`.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("destCidrIp")]
        public Input<string>? DestCidrIp { get; set; }

        [Input("destGroupId")]
        public Input<string>? DestGroupId { get; set; }

        [Input("destGroupOwnerAccount")]
        public Input<string>? DestGroupOwnerAccount { get; set; }

        [Input("destPrefixListId")]
        public Input<string>? DestPrefixListId { get; set; }

        /// <summary>
        /// The transport layer protocol of the Security Group Rule. Valid values: `tcp`, `udp`, `icmp`, `gre`, `all`.
        /// </summary>
        [Input("ipProtocol", required: true)]
        public Input<string> IpProtocol { get; set; } = null!;

        [Input("ipv6DestCidrIp")]
        public Input<string>? Ipv6DestCidrIp { get; set; }

        [Input("ipv6SourceCidrIp")]
        public Input<string>? Ipv6SourceCidrIp { get; set; }

        /// <summary>
        /// Network type, can be either `internet` or `intranet`, the default value is `internet`.
        /// </summary>
        [Input("nicType")]
        public Input<string>? NicType { get; set; }

        /// <summary>
        /// The action of the Security Group Rule that determines whether to allow inbound access. Default value: `accept`. Valid values: `accept`, `drop`.
        /// </summary>
        [Input("policy")]
        public Input<string>? Policy { get; set; }

        /// <summary>
        /// The range of port numbers relevant to the IP protocol. Default to "-1/-1". When the protocol is tcp or udp, each side port number range from 1 to 65535 and '-1/-1' will be invalid.
        /// For example, `1/200` means that the range of the port numbers is 1-200. Other protocols' 'port_range' can only be "-1/-1", and other values will be invalid.
        /// </summary>
        [Input("portRange")]
        public Input<string>? PortRange { get; set; }

        /// <summary>
        /// The priority of the Security Group Rule. Default value: `1`. Valid values: `1` to `100`.
        /// </summary>
        [Input("priority")]
        public Input<int>? Priority { get; set; }

        /// <summary>
        /// The ID of the Security Group.
        /// </summary>
        [Input("securityGroupId", required: true)]
        public Input<string> SecurityGroupId { get; set; } = null!;

        [Input("sourceCidrIp")]
        public Input<string>? SourceCidrIp { get; set; }

        [Input("sourceGroupId")]
        public Input<string>? SourceGroupId { get; set; }

        /// <summary>
        /// The Alibaba Cloud user account Id of the target security group when security groups are authorized across accounts.  This parameter is invalid if `cidr_ip` has already been set.
        /// </summary>
        [Input("sourceGroupOwnerAccount")]
        public Input<string>? SourceGroupOwnerAccount { get; set; }

        [Input("sourcePortRange")]
        public Input<string>? SourcePortRange { get; set; }

        [Input("sourcePrefixListId")]
        public Input<string>? SourcePrefixListId { get; set; }

        /// <summary>
        /// The type of the Security Group Rule. Valid values:
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public SecurityGroupRuleArgs()
        {
        }
        public static new SecurityGroupRuleArgs Empty => new SecurityGroupRuleArgs();
    }

    public sealed class SecurityGroupRuleState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The description of the security group rule. The description can be up to 1 to 512 characters in length. Defaults to null.
        /// 
        /// &gt; **NOTE:**  You must specify one of the following field: `cidr_ip`,`source_security_group_id`,`prefix_list_id`,`ipv6_cidr_ip`.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("destCidrIp")]
        public Input<string>? DestCidrIp { get; set; }

        [Input("destGroupId")]
        public Input<string>? DestGroupId { get; set; }

        [Input("destGroupOwnerAccount")]
        public Input<string>? DestGroupOwnerAccount { get; set; }

        [Input("destPrefixListId")]
        public Input<string>? DestPrefixListId { get; set; }

        /// <summary>
        /// The transport layer protocol of the Security Group Rule. Valid values: `tcp`, `udp`, `icmp`, `gre`, `all`.
        /// </summary>
        [Input("ipProtocol")]
        public Input<string>? IpProtocol { get; set; }

        [Input("ipv6DestCidrIp")]
        public Input<string>? Ipv6DestCidrIp { get; set; }

        [Input("ipv6SourceCidrIp")]
        public Input<string>? Ipv6SourceCidrIp { get; set; }

        /// <summary>
        /// Network type, can be either `internet` or `intranet`, the default value is `internet`.
        /// </summary>
        [Input("nicType")]
        public Input<string>? NicType { get; set; }

        /// <summary>
        /// The action of the Security Group Rule that determines whether to allow inbound access. Default value: `accept`. Valid values: `accept`, `drop`.
        /// </summary>
        [Input("policy")]
        public Input<string>? Policy { get; set; }

        /// <summary>
        /// The range of port numbers relevant to the IP protocol. Default to "-1/-1". When the protocol is tcp or udp, each side port number range from 1 to 65535 and '-1/-1' will be invalid.
        /// For example, `1/200` means that the range of the port numbers is 1-200. Other protocols' 'port_range' can only be "-1/-1", and other values will be invalid.
        /// </summary>
        [Input("portRange")]
        public Input<string>? PortRange { get; set; }

        /// <summary>
        /// The priority of the Security Group Rule. Default value: `1`. Valid values: `1` to `100`.
        /// </summary>
        [Input("priority")]
        public Input<int>? Priority { get; set; }

        /// <summary>
        /// The ID of the Security Group.
        /// </summary>
        [Input("securityGroupId")]
        public Input<string>? SecurityGroupId { get; set; }

        [Input("sourceCidrIp")]
        public Input<string>? SourceCidrIp { get; set; }

        [Input("sourceGroupId")]
        public Input<string>? SourceGroupId { get; set; }

        /// <summary>
        /// The Alibaba Cloud user account Id of the target security group when security groups are authorized across accounts.  This parameter is invalid if `cidr_ip` has already been set.
        /// </summary>
        [Input("sourceGroupOwnerAccount")]
        public Input<string>? SourceGroupOwnerAccount { get; set; }

        [Input("sourcePortRange")]
        public Input<string>? SourcePortRange { get; set; }

        [Input("sourcePrefixListId")]
        public Input<string>? SourcePrefixListId { get; set; }

        /// <summary>
        /// The type of the Security Group Rule. Valid values:
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public SecurityGroupRuleState()
        {
        }
        public static new SecurityGroupRuleState Empty => new SecurityGroupRuleState();
    }
}
