// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * ## Import
 *
 * Anti-DDoS Pro (DdosBgp) Instance can be imported using the id, e.g.
 *
 * ```sh
 * $ pulumi import alicloud:ddos/ddosBgpInstance:DdosBgpInstance example <id>
 * ```
 */
export class DdosBgpInstance extends pulumi.CustomResource {
    /**
     * Get an existing DdosBgpInstance resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DdosBgpInstanceState, opts?: pulumi.CustomResourceOptions): DdosBgpInstance {
        return new DdosBgpInstance(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'alicloud:ddos/ddosBgpInstance:DdosBgpInstance';

    /**
     * Returns true if the given object is an instance of DdosBgpInstance.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DdosBgpInstance {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DdosBgpInstance.__pulumiType;
    }

    /**
     * The bandwidth of the package configuration.
     */
    public readonly bandwidth!: pulumi.Output<number>;
    /**
     * The basic protection bandwidth of the Anti-DDoS Origin Enterprise instance. Default value: `20`. Valid values: `20`.
     */
    public readonly baseBandwidth!: pulumi.Output<number | undefined>;
    /**
     * The name of the instance.
     */
    public readonly instanceName!: pulumi.Output<string>;
    /**
     * The number of IP addresses that can be protected by the Anti-DDoS Origin Enterprise instance.
     */
    public readonly ipCount!: pulumi.Output<number>;
    /**
     * The protection IP address type of the protection package. Valid values:
     * - `IPv4`
     * - `IPv6`
     */
    public readonly ipType!: pulumi.Output<string>;
    /**
     * Field `name` has been deprecated from provider version 1.259.0. New field `instanceName` instead.
     *
     * @deprecated Field `name` has been deprecated from provider version 1.259.0. New field `instanceName` instead.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The normal clean bandwidth. Unit: Mbit/s.
     */
    public readonly normalBandwidth!: pulumi.Output<number>;
    /**
     * The duration that you will buy Ddosbgp instance (in month). Valid values: [1~9], 12, 24, 36. Default to 12. At present, the provider does not support modify "period".
     */
    public readonly period!: pulumi.Output<number | undefined>;
    /**
     * Resource Group ID
     */
    public readonly resourceGroupId!: pulumi.Output<string>;
    /**
     * (Available since v1.259.0) The status of the Instance.
     */
    public /*out*/ readonly status!: pulumi.Output<string>;
    /**
     * The key of the tag that is added to the Anti-DDoS Origin instance.
     */
    public readonly tags!: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * The protection package type of the DDoS native protection instance. Default value: `Enterprise`. Valid values: `Enterprise`, `Professional`.
     */
    public readonly type!: pulumi.Output<string>;

    /**
     * Create a DdosBgpInstance resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DdosBgpInstanceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DdosBgpInstanceArgs | DdosBgpInstanceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DdosBgpInstanceState | undefined;
            resourceInputs["bandwidth"] = state ? state.bandwidth : undefined;
            resourceInputs["baseBandwidth"] = state ? state.baseBandwidth : undefined;
            resourceInputs["instanceName"] = state ? state.instanceName : undefined;
            resourceInputs["ipCount"] = state ? state.ipCount : undefined;
            resourceInputs["ipType"] = state ? state.ipType : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["normalBandwidth"] = state ? state.normalBandwidth : undefined;
            resourceInputs["period"] = state ? state.period : undefined;
            resourceInputs["resourceGroupId"] = state ? state.resourceGroupId : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
            resourceInputs["type"] = state ? state.type : undefined;
        } else {
            const args = argsOrState as DdosBgpInstanceArgs | undefined;
            if ((!args || args.bandwidth === undefined) && !opts.urn) {
                throw new Error("Missing required property 'bandwidth'");
            }
            if ((!args || args.ipCount === undefined) && !opts.urn) {
                throw new Error("Missing required property 'ipCount'");
            }
            if ((!args || args.ipType === undefined) && !opts.urn) {
                throw new Error("Missing required property 'ipType'");
            }
            if ((!args || args.normalBandwidth === undefined) && !opts.urn) {
                throw new Error("Missing required property 'normalBandwidth'");
            }
            resourceInputs["bandwidth"] = args ? args.bandwidth : undefined;
            resourceInputs["baseBandwidth"] = args ? args.baseBandwidth : undefined;
            resourceInputs["instanceName"] = args ? args.instanceName : undefined;
            resourceInputs["ipCount"] = args ? args.ipCount : undefined;
            resourceInputs["ipType"] = args ? args.ipType : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["normalBandwidth"] = args ? args.normalBandwidth : undefined;
            resourceInputs["period"] = args ? args.period : undefined;
            resourceInputs["resourceGroupId"] = args ? args.resourceGroupId : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
            resourceInputs["type"] = args ? args.type : undefined;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const aliasOpts = { aliases: [{ type: "alicloud:dns/ddosBgpInstance:DdosBgpInstance" }] };
        opts = pulumi.mergeOptions(opts, aliasOpts);
        super(DdosBgpInstance.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering DdosBgpInstance resources.
 */
export interface DdosBgpInstanceState {
    /**
     * The bandwidth of the package configuration.
     */
    bandwidth?: pulumi.Input<number>;
    /**
     * The basic protection bandwidth of the Anti-DDoS Origin Enterprise instance. Default value: `20`. Valid values: `20`.
     */
    baseBandwidth?: pulumi.Input<number>;
    /**
     * The name of the instance.
     */
    instanceName?: pulumi.Input<string>;
    /**
     * The number of IP addresses that can be protected by the Anti-DDoS Origin Enterprise instance.
     */
    ipCount?: pulumi.Input<number>;
    /**
     * The protection IP address type of the protection package. Valid values:
     * - `IPv4`
     * - `IPv6`
     */
    ipType?: pulumi.Input<string>;
    /**
     * Field `name` has been deprecated from provider version 1.259.0. New field `instanceName` instead.
     *
     * @deprecated Field `name` has been deprecated from provider version 1.259.0. New field `instanceName` instead.
     */
    name?: pulumi.Input<string>;
    /**
     * The normal clean bandwidth. Unit: Mbit/s.
     */
    normalBandwidth?: pulumi.Input<number>;
    /**
     * The duration that you will buy Ddosbgp instance (in month). Valid values: [1~9], 12, 24, 36. Default to 12. At present, the provider does not support modify "period".
     */
    period?: pulumi.Input<number>;
    /**
     * Resource Group ID
     */
    resourceGroupId?: pulumi.Input<string>;
    /**
     * (Available since v1.259.0) The status of the Instance.
     */
    status?: pulumi.Input<string>;
    /**
     * The key of the tag that is added to the Anti-DDoS Origin instance.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The protection package type of the DDoS native protection instance. Default value: `Enterprise`. Valid values: `Enterprise`, `Professional`.
     */
    type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a DdosBgpInstance resource.
 */
export interface DdosBgpInstanceArgs {
    /**
     * The bandwidth of the package configuration.
     */
    bandwidth: pulumi.Input<number>;
    /**
     * The basic protection bandwidth of the Anti-DDoS Origin Enterprise instance. Default value: `20`. Valid values: `20`.
     */
    baseBandwidth?: pulumi.Input<number>;
    /**
     * The name of the instance.
     */
    instanceName?: pulumi.Input<string>;
    /**
     * The number of IP addresses that can be protected by the Anti-DDoS Origin Enterprise instance.
     */
    ipCount: pulumi.Input<number>;
    /**
     * The protection IP address type of the protection package. Valid values:
     * - `IPv4`
     * - `IPv6`
     */
    ipType: pulumi.Input<string>;
    /**
     * Field `name` has been deprecated from provider version 1.259.0. New field `instanceName` instead.
     *
     * @deprecated Field `name` has been deprecated from provider version 1.259.0. New field `instanceName` instead.
     */
    name?: pulumi.Input<string>;
    /**
     * The normal clean bandwidth. Unit: Mbit/s.
     */
    normalBandwidth: pulumi.Input<number>;
    /**
     * The duration that you will buy Ddosbgp instance (in month). Valid values: [1~9], 12, 24, 36. Default to 12. At present, the provider does not support modify "period".
     */
    period?: pulumi.Input<number>;
    /**
     * Resource Group ID
     */
    resourceGroupId?: pulumi.Input<string>;
    /**
     * The key of the tag that is added to the Anti-DDoS Origin instance.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The protection package type of the DDoS native protection instance. Default value: `Enterprise`. Valid values: `Enterprise`, `Professional`.
     */
    type?: pulumi.Input<string>;
}
