// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ecs

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-alicloud/sdk/v3/go/alicloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Provides a Security Group Rule resource.
//
// For information about Security Group Rule and how to use it, see [What is Rule](https://www.alibabacloud.com/help/en/ecs/user-guide/security-group-rules).
//
// > **NOTE:** Available since v0.1.0.
//
// Represents a single `ingress` or `egress` group rule, which can be added to external Security Groups.
//
// > **NOTE:**  `nicType` should set to `intranet` when security group type is `vpc` or specifying the `sourceSecurityGroupId`. In this situation it does not distinguish between intranet and internet, the rule is effective on them both.
//
// ## Import
//
// Security Group Rule can be imported using the id, e.g.
//
// ```sh
// $ pulumi import alicloud:ecs/securityGroupRule:SecurityGroupRule example <id>
// ```
type SecurityGroupRule struct {
	pulumi.CustomResourceState

	// The description of the security group rule. The description can be up to 1 to 512 characters in length. Defaults to null.
	//
	// > **NOTE:**  You must specify one of the following field: `cidrIp`,`sourceSecurityGroupId`,`prefixListId`,`ipv6CidrIp`.
	Description           pulumi.StringPtrOutput `pulumi:"description"`
	DestCidrIp            pulumi.StringPtrOutput `pulumi:"destCidrIp"`
	DestGroupId           pulumi.StringPtrOutput `pulumi:"destGroupId"`
	DestGroupOwnerAccount pulumi.StringPtrOutput `pulumi:"destGroupOwnerAccount"`
	DestPrefixListId      pulumi.StringOutput    `pulumi:"destPrefixListId"`
	// The transport layer protocol of the Security Group Rule. Valid values: `tcp`, `udp`, `icmp`, `gre`, `all`.
	IpProtocol       pulumi.StringOutput    `pulumi:"ipProtocol"`
	Ipv6DestCidrIp   pulumi.StringPtrOutput `pulumi:"ipv6DestCidrIp"`
	Ipv6SourceCidrIp pulumi.StringPtrOutput `pulumi:"ipv6SourceCidrIp"`
	// Network type, can be either `internet` or `intranet`, the default value is `internet`.
	NicType pulumi.StringOutput `pulumi:"nicType"`
	// The action of the Security Group Rule that determines whether to allow inbound access. Default value: `accept`. Valid values: `accept`, `drop`.
	Policy pulumi.StringPtrOutput `pulumi:"policy"`
	// The range of port numbers relevant to the IP protocol. Default to "-1/-1". When the protocol is tcp or udp, each side port number range from 1 to 65535 and '-1/-1' will be invalid.
	// For example, `1/200` means that the range of the port numbers is 1-200. Other protocols' 'port_range' can only be "-1/-1", and other values will be invalid.
	PortRange pulumi.StringPtrOutput `pulumi:"portRange"`
	// The priority of the Security Group Rule. Default value: `1`. Valid values: `1` to `100`.
	Priority pulumi.IntPtrOutput `pulumi:"priority"`
	// The ID of the Security Group.
	SecurityGroupId pulumi.StringOutput    `pulumi:"securityGroupId"`
	SourceCidrIp    pulumi.StringPtrOutput `pulumi:"sourceCidrIp"`
	SourceGroupId   pulumi.StringPtrOutput `pulumi:"sourceGroupId"`
	// The Alibaba Cloud user account Id of the target security group when security groups are authorized across accounts.  This parameter is invalid if `cidrIp` has already been set.
	SourceGroupOwnerAccount pulumi.StringPtrOutput `pulumi:"sourceGroupOwnerAccount"`
	SourcePortRange         pulumi.StringPtrOutput `pulumi:"sourcePortRange"`
	SourcePrefixListId      pulumi.StringOutput    `pulumi:"sourcePrefixListId"`
	// The type of the Security Group Rule. Valid values:
	Type pulumi.StringOutput `pulumi:"type"`
}

// NewSecurityGroupRule registers a new resource with the given unique name, arguments, and options.
func NewSecurityGroupRule(ctx *pulumi.Context,
	name string, args *SecurityGroupRuleArgs, opts ...pulumi.ResourceOption) (*SecurityGroupRule, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.IpProtocol == nil {
		return nil, errors.New("invalid value for required argument 'IpProtocol'")
	}
	if args.SecurityGroupId == nil {
		return nil, errors.New("invalid value for required argument 'SecurityGroupId'")
	}
	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SecurityGroupRule
	err := ctx.RegisterResource("alicloud:ecs/securityGroupRule:SecurityGroupRule", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSecurityGroupRule gets an existing SecurityGroupRule resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSecurityGroupRule(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SecurityGroupRuleState, opts ...pulumi.ResourceOption) (*SecurityGroupRule, error) {
	var resource SecurityGroupRule
	err := ctx.ReadResource("alicloud:ecs/securityGroupRule:SecurityGroupRule", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SecurityGroupRule resources.
type securityGroupRuleState struct {
	// The description of the security group rule. The description can be up to 1 to 512 characters in length. Defaults to null.
	//
	// > **NOTE:**  You must specify one of the following field: `cidrIp`,`sourceSecurityGroupId`,`prefixListId`,`ipv6CidrIp`.
	Description           *string `pulumi:"description"`
	DestCidrIp            *string `pulumi:"destCidrIp"`
	DestGroupId           *string `pulumi:"destGroupId"`
	DestGroupOwnerAccount *string `pulumi:"destGroupOwnerAccount"`
	DestPrefixListId      *string `pulumi:"destPrefixListId"`
	// The transport layer protocol of the Security Group Rule. Valid values: `tcp`, `udp`, `icmp`, `gre`, `all`.
	IpProtocol       *string `pulumi:"ipProtocol"`
	Ipv6DestCidrIp   *string `pulumi:"ipv6DestCidrIp"`
	Ipv6SourceCidrIp *string `pulumi:"ipv6SourceCidrIp"`
	// Network type, can be either `internet` or `intranet`, the default value is `internet`.
	NicType *string `pulumi:"nicType"`
	// The action of the Security Group Rule that determines whether to allow inbound access. Default value: `accept`. Valid values: `accept`, `drop`.
	Policy *string `pulumi:"policy"`
	// The range of port numbers relevant to the IP protocol. Default to "-1/-1". When the protocol is tcp or udp, each side port number range from 1 to 65535 and '-1/-1' will be invalid.
	// For example, `1/200` means that the range of the port numbers is 1-200. Other protocols' 'port_range' can only be "-1/-1", and other values will be invalid.
	PortRange *string `pulumi:"portRange"`
	// The priority of the Security Group Rule. Default value: `1`. Valid values: `1` to `100`.
	Priority *int `pulumi:"priority"`
	// The ID of the Security Group.
	SecurityGroupId *string `pulumi:"securityGroupId"`
	SourceCidrIp    *string `pulumi:"sourceCidrIp"`
	SourceGroupId   *string `pulumi:"sourceGroupId"`
	// The Alibaba Cloud user account Id of the target security group when security groups are authorized across accounts.  This parameter is invalid if `cidrIp` has already been set.
	SourceGroupOwnerAccount *string `pulumi:"sourceGroupOwnerAccount"`
	SourcePortRange         *string `pulumi:"sourcePortRange"`
	SourcePrefixListId      *string `pulumi:"sourcePrefixListId"`
	// The type of the Security Group Rule. Valid values:
	Type *string `pulumi:"type"`
}

type SecurityGroupRuleState struct {
	// The description of the security group rule. The description can be up to 1 to 512 characters in length. Defaults to null.
	//
	// > **NOTE:**  You must specify one of the following field: `cidrIp`,`sourceSecurityGroupId`,`prefixListId`,`ipv6CidrIp`.
	Description           pulumi.StringPtrInput
	DestCidrIp            pulumi.StringPtrInput
	DestGroupId           pulumi.StringPtrInput
	DestGroupOwnerAccount pulumi.StringPtrInput
	DestPrefixListId      pulumi.StringPtrInput
	// The transport layer protocol of the Security Group Rule. Valid values: `tcp`, `udp`, `icmp`, `gre`, `all`.
	IpProtocol       pulumi.StringPtrInput
	Ipv6DestCidrIp   pulumi.StringPtrInput
	Ipv6SourceCidrIp pulumi.StringPtrInput
	// Network type, can be either `internet` or `intranet`, the default value is `internet`.
	NicType pulumi.StringPtrInput
	// The action of the Security Group Rule that determines whether to allow inbound access. Default value: `accept`. Valid values: `accept`, `drop`.
	Policy pulumi.StringPtrInput
	// The range of port numbers relevant to the IP protocol. Default to "-1/-1". When the protocol is tcp or udp, each side port number range from 1 to 65535 and '-1/-1' will be invalid.
	// For example, `1/200` means that the range of the port numbers is 1-200. Other protocols' 'port_range' can only be "-1/-1", and other values will be invalid.
	PortRange pulumi.StringPtrInput
	// The priority of the Security Group Rule. Default value: `1`. Valid values: `1` to `100`.
	Priority pulumi.IntPtrInput
	// The ID of the Security Group.
	SecurityGroupId pulumi.StringPtrInput
	SourceCidrIp    pulumi.StringPtrInput
	SourceGroupId   pulumi.StringPtrInput
	// The Alibaba Cloud user account Id of the target security group when security groups are authorized across accounts.  This parameter is invalid if `cidrIp` has already been set.
	SourceGroupOwnerAccount pulumi.StringPtrInput
	SourcePortRange         pulumi.StringPtrInput
	SourcePrefixListId      pulumi.StringPtrInput
	// The type of the Security Group Rule. Valid values:
	Type pulumi.StringPtrInput
}

func (SecurityGroupRuleState) ElementType() reflect.Type {
	return reflect.TypeOf((*securityGroupRuleState)(nil)).Elem()
}

type securityGroupRuleArgs struct {
	// The description of the security group rule. The description can be up to 1 to 512 characters in length. Defaults to null.
	//
	// > **NOTE:**  You must specify one of the following field: `cidrIp`,`sourceSecurityGroupId`,`prefixListId`,`ipv6CidrIp`.
	Description           *string `pulumi:"description"`
	DestCidrIp            *string `pulumi:"destCidrIp"`
	DestGroupId           *string `pulumi:"destGroupId"`
	DestGroupOwnerAccount *string `pulumi:"destGroupOwnerAccount"`
	DestPrefixListId      *string `pulumi:"destPrefixListId"`
	// The transport layer protocol of the Security Group Rule. Valid values: `tcp`, `udp`, `icmp`, `gre`, `all`.
	IpProtocol       string  `pulumi:"ipProtocol"`
	Ipv6DestCidrIp   *string `pulumi:"ipv6DestCidrIp"`
	Ipv6SourceCidrIp *string `pulumi:"ipv6SourceCidrIp"`
	// Network type, can be either `internet` or `intranet`, the default value is `internet`.
	NicType *string `pulumi:"nicType"`
	// The action of the Security Group Rule that determines whether to allow inbound access. Default value: `accept`. Valid values: `accept`, `drop`.
	Policy *string `pulumi:"policy"`
	// The range of port numbers relevant to the IP protocol. Default to "-1/-1". When the protocol is tcp or udp, each side port number range from 1 to 65535 and '-1/-1' will be invalid.
	// For example, `1/200` means that the range of the port numbers is 1-200. Other protocols' 'port_range' can only be "-1/-1", and other values will be invalid.
	PortRange *string `pulumi:"portRange"`
	// The priority of the Security Group Rule. Default value: `1`. Valid values: `1` to `100`.
	Priority *int `pulumi:"priority"`
	// The ID of the Security Group.
	SecurityGroupId string  `pulumi:"securityGroupId"`
	SourceCidrIp    *string `pulumi:"sourceCidrIp"`
	SourceGroupId   *string `pulumi:"sourceGroupId"`
	// The Alibaba Cloud user account Id of the target security group when security groups are authorized across accounts.  This parameter is invalid if `cidrIp` has already been set.
	SourceGroupOwnerAccount *string `pulumi:"sourceGroupOwnerAccount"`
	SourcePortRange         *string `pulumi:"sourcePortRange"`
	SourcePrefixListId      *string `pulumi:"sourcePrefixListId"`
	// The type of the Security Group Rule. Valid values:
	Type string `pulumi:"type"`
}

// The set of arguments for constructing a SecurityGroupRule resource.
type SecurityGroupRuleArgs struct {
	// The description of the security group rule. The description can be up to 1 to 512 characters in length. Defaults to null.
	//
	// > **NOTE:**  You must specify one of the following field: `cidrIp`,`sourceSecurityGroupId`,`prefixListId`,`ipv6CidrIp`.
	Description           pulumi.StringPtrInput
	DestCidrIp            pulumi.StringPtrInput
	DestGroupId           pulumi.StringPtrInput
	DestGroupOwnerAccount pulumi.StringPtrInput
	DestPrefixListId      pulumi.StringPtrInput
	// The transport layer protocol of the Security Group Rule. Valid values: `tcp`, `udp`, `icmp`, `gre`, `all`.
	IpProtocol       pulumi.StringInput
	Ipv6DestCidrIp   pulumi.StringPtrInput
	Ipv6SourceCidrIp pulumi.StringPtrInput
	// Network type, can be either `internet` or `intranet`, the default value is `internet`.
	NicType pulumi.StringPtrInput
	// The action of the Security Group Rule that determines whether to allow inbound access. Default value: `accept`. Valid values: `accept`, `drop`.
	Policy pulumi.StringPtrInput
	// The range of port numbers relevant to the IP protocol. Default to "-1/-1". When the protocol is tcp or udp, each side port number range from 1 to 65535 and '-1/-1' will be invalid.
	// For example, `1/200` means that the range of the port numbers is 1-200. Other protocols' 'port_range' can only be "-1/-1", and other values will be invalid.
	PortRange pulumi.StringPtrInput
	// The priority of the Security Group Rule. Default value: `1`. Valid values: `1` to `100`.
	Priority pulumi.IntPtrInput
	// The ID of the Security Group.
	SecurityGroupId pulumi.StringInput
	SourceCidrIp    pulumi.StringPtrInput
	SourceGroupId   pulumi.StringPtrInput
	// The Alibaba Cloud user account Id of the target security group when security groups are authorized across accounts.  This parameter is invalid if `cidrIp` has already been set.
	SourceGroupOwnerAccount pulumi.StringPtrInput
	SourcePortRange         pulumi.StringPtrInput
	SourcePrefixListId      pulumi.StringPtrInput
	// The type of the Security Group Rule. Valid values:
	Type pulumi.StringInput
}

func (SecurityGroupRuleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*securityGroupRuleArgs)(nil)).Elem()
}

type SecurityGroupRuleInput interface {
	pulumi.Input

	ToSecurityGroupRuleOutput() SecurityGroupRuleOutput
	ToSecurityGroupRuleOutputWithContext(ctx context.Context) SecurityGroupRuleOutput
}

func (*SecurityGroupRule) ElementType() reflect.Type {
	return reflect.TypeOf((**SecurityGroupRule)(nil)).Elem()
}

func (i *SecurityGroupRule) ToSecurityGroupRuleOutput() SecurityGroupRuleOutput {
	return i.ToSecurityGroupRuleOutputWithContext(context.Background())
}

func (i *SecurityGroupRule) ToSecurityGroupRuleOutputWithContext(ctx context.Context) SecurityGroupRuleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecurityGroupRuleOutput)
}

// SecurityGroupRuleArrayInput is an input type that accepts SecurityGroupRuleArray and SecurityGroupRuleArrayOutput values.
// You can construct a concrete instance of `SecurityGroupRuleArrayInput` via:
//
//	SecurityGroupRuleArray{ SecurityGroupRuleArgs{...} }
type SecurityGroupRuleArrayInput interface {
	pulumi.Input

	ToSecurityGroupRuleArrayOutput() SecurityGroupRuleArrayOutput
	ToSecurityGroupRuleArrayOutputWithContext(context.Context) SecurityGroupRuleArrayOutput
}

type SecurityGroupRuleArray []SecurityGroupRuleInput

func (SecurityGroupRuleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SecurityGroupRule)(nil)).Elem()
}

func (i SecurityGroupRuleArray) ToSecurityGroupRuleArrayOutput() SecurityGroupRuleArrayOutput {
	return i.ToSecurityGroupRuleArrayOutputWithContext(context.Background())
}

func (i SecurityGroupRuleArray) ToSecurityGroupRuleArrayOutputWithContext(ctx context.Context) SecurityGroupRuleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecurityGroupRuleArrayOutput)
}

// SecurityGroupRuleMapInput is an input type that accepts SecurityGroupRuleMap and SecurityGroupRuleMapOutput values.
// You can construct a concrete instance of `SecurityGroupRuleMapInput` via:
//
//	SecurityGroupRuleMap{ "key": SecurityGroupRuleArgs{...} }
type SecurityGroupRuleMapInput interface {
	pulumi.Input

	ToSecurityGroupRuleMapOutput() SecurityGroupRuleMapOutput
	ToSecurityGroupRuleMapOutputWithContext(context.Context) SecurityGroupRuleMapOutput
}

type SecurityGroupRuleMap map[string]SecurityGroupRuleInput

func (SecurityGroupRuleMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SecurityGroupRule)(nil)).Elem()
}

func (i SecurityGroupRuleMap) ToSecurityGroupRuleMapOutput() SecurityGroupRuleMapOutput {
	return i.ToSecurityGroupRuleMapOutputWithContext(context.Background())
}

func (i SecurityGroupRuleMap) ToSecurityGroupRuleMapOutputWithContext(ctx context.Context) SecurityGroupRuleMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecurityGroupRuleMapOutput)
}

type SecurityGroupRuleOutput struct{ *pulumi.OutputState }

func (SecurityGroupRuleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SecurityGroupRule)(nil)).Elem()
}

func (o SecurityGroupRuleOutput) ToSecurityGroupRuleOutput() SecurityGroupRuleOutput {
	return o
}

func (o SecurityGroupRuleOutput) ToSecurityGroupRuleOutputWithContext(ctx context.Context) SecurityGroupRuleOutput {
	return o
}

// The description of the security group rule. The description can be up to 1 to 512 characters in length. Defaults to null.
//
// > **NOTE:**  You must specify one of the following field: `cidrIp`,`sourceSecurityGroupId`,`prefixListId`,`ipv6CidrIp`.
func (o SecurityGroupRuleOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SecurityGroupRule) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

func (o SecurityGroupRuleOutput) DestCidrIp() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SecurityGroupRule) pulumi.StringPtrOutput { return v.DestCidrIp }).(pulumi.StringPtrOutput)
}

func (o SecurityGroupRuleOutput) DestGroupId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SecurityGroupRule) pulumi.StringPtrOutput { return v.DestGroupId }).(pulumi.StringPtrOutput)
}

func (o SecurityGroupRuleOutput) DestGroupOwnerAccount() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SecurityGroupRule) pulumi.StringPtrOutput { return v.DestGroupOwnerAccount }).(pulumi.StringPtrOutput)
}

func (o SecurityGroupRuleOutput) DestPrefixListId() pulumi.StringOutput {
	return o.ApplyT(func(v *SecurityGroupRule) pulumi.StringOutput { return v.DestPrefixListId }).(pulumi.StringOutput)
}

// The transport layer protocol of the Security Group Rule. Valid values: `tcp`, `udp`, `icmp`, `gre`, `all`.
func (o SecurityGroupRuleOutput) IpProtocol() pulumi.StringOutput {
	return o.ApplyT(func(v *SecurityGroupRule) pulumi.StringOutput { return v.IpProtocol }).(pulumi.StringOutput)
}

func (o SecurityGroupRuleOutput) Ipv6DestCidrIp() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SecurityGroupRule) pulumi.StringPtrOutput { return v.Ipv6DestCidrIp }).(pulumi.StringPtrOutput)
}

func (o SecurityGroupRuleOutput) Ipv6SourceCidrIp() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SecurityGroupRule) pulumi.StringPtrOutput { return v.Ipv6SourceCidrIp }).(pulumi.StringPtrOutput)
}

// Network type, can be either `internet` or `intranet`, the default value is `internet`.
func (o SecurityGroupRuleOutput) NicType() pulumi.StringOutput {
	return o.ApplyT(func(v *SecurityGroupRule) pulumi.StringOutput { return v.NicType }).(pulumi.StringOutput)
}

// The action of the Security Group Rule that determines whether to allow inbound access. Default value: `accept`. Valid values: `accept`, `drop`.
func (o SecurityGroupRuleOutput) Policy() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SecurityGroupRule) pulumi.StringPtrOutput { return v.Policy }).(pulumi.StringPtrOutput)
}

// The range of port numbers relevant to the IP protocol. Default to "-1/-1". When the protocol is tcp or udp, each side port number range from 1 to 65535 and '-1/-1' will be invalid.
// For example, `1/200` means that the range of the port numbers is 1-200. Other protocols' 'port_range' can only be "-1/-1", and other values will be invalid.
func (o SecurityGroupRuleOutput) PortRange() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SecurityGroupRule) pulumi.StringPtrOutput { return v.PortRange }).(pulumi.StringPtrOutput)
}

// The priority of the Security Group Rule. Default value: `1`. Valid values: `1` to `100`.
func (o SecurityGroupRuleOutput) Priority() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *SecurityGroupRule) pulumi.IntPtrOutput { return v.Priority }).(pulumi.IntPtrOutput)
}

// The ID of the Security Group.
func (o SecurityGroupRuleOutput) SecurityGroupId() pulumi.StringOutput {
	return o.ApplyT(func(v *SecurityGroupRule) pulumi.StringOutput { return v.SecurityGroupId }).(pulumi.StringOutput)
}

func (o SecurityGroupRuleOutput) SourceCidrIp() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SecurityGroupRule) pulumi.StringPtrOutput { return v.SourceCidrIp }).(pulumi.StringPtrOutput)
}

func (o SecurityGroupRuleOutput) SourceGroupId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SecurityGroupRule) pulumi.StringPtrOutput { return v.SourceGroupId }).(pulumi.StringPtrOutput)
}

// The Alibaba Cloud user account Id of the target security group when security groups are authorized across accounts.  This parameter is invalid if `cidrIp` has already been set.
func (o SecurityGroupRuleOutput) SourceGroupOwnerAccount() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SecurityGroupRule) pulumi.StringPtrOutput { return v.SourceGroupOwnerAccount }).(pulumi.StringPtrOutput)
}

func (o SecurityGroupRuleOutput) SourcePortRange() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SecurityGroupRule) pulumi.StringPtrOutput { return v.SourcePortRange }).(pulumi.StringPtrOutput)
}

func (o SecurityGroupRuleOutput) SourcePrefixListId() pulumi.StringOutput {
	return o.ApplyT(func(v *SecurityGroupRule) pulumi.StringOutput { return v.SourcePrefixListId }).(pulumi.StringOutput)
}

// The type of the Security Group Rule. Valid values:
func (o SecurityGroupRuleOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *SecurityGroupRule) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

type SecurityGroupRuleArrayOutput struct{ *pulumi.OutputState }

func (SecurityGroupRuleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SecurityGroupRule)(nil)).Elem()
}

func (o SecurityGroupRuleArrayOutput) ToSecurityGroupRuleArrayOutput() SecurityGroupRuleArrayOutput {
	return o
}

func (o SecurityGroupRuleArrayOutput) ToSecurityGroupRuleArrayOutputWithContext(ctx context.Context) SecurityGroupRuleArrayOutput {
	return o
}

func (o SecurityGroupRuleArrayOutput) Index(i pulumi.IntInput) SecurityGroupRuleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SecurityGroupRule {
		return vs[0].([]*SecurityGroupRule)[vs[1].(int)]
	}).(SecurityGroupRuleOutput)
}

type SecurityGroupRuleMapOutput struct{ *pulumi.OutputState }

func (SecurityGroupRuleMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SecurityGroupRule)(nil)).Elem()
}

func (o SecurityGroupRuleMapOutput) ToSecurityGroupRuleMapOutput() SecurityGroupRuleMapOutput {
	return o
}

func (o SecurityGroupRuleMapOutput) ToSecurityGroupRuleMapOutputWithContext(ctx context.Context) SecurityGroupRuleMapOutput {
	return o
}

func (o SecurityGroupRuleMapOutput) MapIndex(k pulumi.StringInput) SecurityGroupRuleOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SecurityGroupRule {
		return vs[0].(map[string]*SecurityGroupRule)[vs[1].(string)]
	}).(SecurityGroupRuleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SecurityGroupRuleInput)(nil)).Elem(), &SecurityGroupRule{})
	pulumi.RegisterInputType(reflect.TypeOf((*SecurityGroupRuleArrayInput)(nil)).Elem(), SecurityGroupRuleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SecurityGroupRuleMapInput)(nil)).Elem(), SecurityGroupRuleMap{})
	pulumi.RegisterOutputType(SecurityGroupRuleOutput{})
	pulumi.RegisterOutputType(SecurityGroupRuleArrayOutput{})
	pulumi.RegisterOutputType(SecurityGroupRuleMapOutput{})
}
