// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.alicloud.pvtz.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ZoneAttachmentVpc {
    /**
     * @return The region of the vpc. If not set, the current region will instead of.
     * 
     */
    private @Nullable String regionId;
    /**
     * @return The Id of the vpc.
     * 
     */
    private String vpcId;
    private @Nullable String vpcType;

    private ZoneAttachmentVpc() {}
    /**
     * @return The region of the vpc. If not set, the current region will instead of.
     * 
     */
    public Optional<String> regionId() {
        return Optional.ofNullable(this.regionId);
    }
    /**
     * @return The Id of the vpc.
     * 
     */
    public String vpcId() {
        return this.vpcId;
    }
    public Optional<String> vpcType() {
        return Optional.ofNullable(this.vpcType);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ZoneAttachmentVpc defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String regionId;
        private String vpcId;
        private @Nullable String vpcType;
        public Builder() {}
        public Builder(ZoneAttachmentVpc defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.regionId = defaults.regionId;
    	      this.vpcId = defaults.vpcId;
    	      this.vpcType = defaults.vpcType;
        }

        @CustomType.Setter
        public Builder regionId(@Nullable String regionId) {

            this.regionId = regionId;
            return this;
        }
        @CustomType.Setter
        public Builder vpcId(String vpcId) {
            if (vpcId == null) {
              throw new MissingRequiredPropertyException("ZoneAttachmentVpc", "vpcId");
            }
            this.vpcId = vpcId;
            return this;
        }
        @CustomType.Setter
        public Builder vpcType(@Nullable String vpcType) {

            this.vpcType = vpcType;
            return this;
        }
        public ZoneAttachmentVpc build() {
            final var _resultValue = new ZoneAttachmentVpc();
            _resultValue.regionId = regionId;
            _resultValue.vpcId = vpcId;
            _resultValue.vpcType = vpcType;
            return _resultValue;
        }
    }
}
