// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package arms

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-alicloud/sdk/v3/go/alicloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides the ARMS Addon Releases of the current Alibaba Cloud user.
//
// > **NOTE:** Available since v1.258.0.
func GetAddonReleases(ctx *pulumi.Context, args *GetAddonReleasesArgs, opts ...pulumi.InvokeOption) (*GetAddonReleasesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetAddonReleasesResult
	err := ctx.Invoke("alicloud:arms/getAddonReleases:getAddonReleases", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAddonReleases.
type GetAddonReleasesArgs struct {
	// The environment ID.
	EnvironmentId string `pulumi:"environmentId"`
	// A list of ARMS Addon Release IDs.
	Ids []string `pulumi:"ids"`
	// A regex string to filter results by ARMS Addon Release name.
	NameRegex *string `pulumi:"nameRegex"`
	// File name where to save data source results (after running `pulumi preview`).
	OutputFile *string `pulumi:"outputFile"`
}

// A collection of values returned by getAddonReleases.
type GetAddonReleasesResult struct {
	// The environment ID.
	EnvironmentId string `pulumi:"environmentId"`
	// The provider-assigned unique ID for this managed resource.
	Id        string   `pulumi:"id"`
	Ids       []string `pulumi:"ids"`
	NameRegex *string  `pulumi:"nameRegex"`
	// A list of ARMS Addon Release names.
	Names      []string `pulumi:"names"`
	OutputFile *string  `pulumi:"outputFile"`
	// A list of ARMS Addon Releases. Each element contains the following attributes:
	Releases []GetAddonReleasesRelease `pulumi:"releases"`
}

func GetAddonReleasesOutput(ctx *pulumi.Context, args GetAddonReleasesOutputArgs, opts ...pulumi.InvokeOption) GetAddonReleasesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetAddonReleasesResultOutput, error) {
			args := v.(GetAddonReleasesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("alicloud:arms/getAddonReleases:getAddonReleases", args, GetAddonReleasesResultOutput{}, options).(GetAddonReleasesResultOutput), nil
		}).(GetAddonReleasesResultOutput)
}

// A collection of arguments for invoking getAddonReleases.
type GetAddonReleasesOutputArgs struct {
	// The environment ID.
	EnvironmentId pulumi.StringInput `pulumi:"environmentId"`
	// A list of ARMS Addon Release IDs.
	Ids pulumi.StringArrayInput `pulumi:"ids"`
	// A regex string to filter results by ARMS Addon Release name.
	NameRegex pulumi.StringPtrInput `pulumi:"nameRegex"`
	// File name where to save data source results (after running `pulumi preview`).
	OutputFile pulumi.StringPtrInput `pulumi:"outputFile"`
}

func (GetAddonReleasesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAddonReleasesArgs)(nil)).Elem()
}

// A collection of values returned by getAddonReleases.
type GetAddonReleasesResultOutput struct{ *pulumi.OutputState }

func (GetAddonReleasesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAddonReleasesResult)(nil)).Elem()
}

func (o GetAddonReleasesResultOutput) ToGetAddonReleasesResultOutput() GetAddonReleasesResultOutput {
	return o
}

func (o GetAddonReleasesResultOutput) ToGetAddonReleasesResultOutputWithContext(ctx context.Context) GetAddonReleasesResultOutput {
	return o
}

// The environment ID.
func (o GetAddonReleasesResultOutput) EnvironmentId() pulumi.StringOutput {
	return o.ApplyT(func(v GetAddonReleasesResult) string { return v.EnvironmentId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetAddonReleasesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetAddonReleasesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetAddonReleasesResultOutput) Ids() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetAddonReleasesResult) []string { return v.Ids }).(pulumi.StringArrayOutput)
}

func (o GetAddonReleasesResultOutput) NameRegex() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetAddonReleasesResult) *string { return v.NameRegex }).(pulumi.StringPtrOutput)
}

// A list of ARMS Addon Release names.
func (o GetAddonReleasesResultOutput) Names() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetAddonReleasesResult) []string { return v.Names }).(pulumi.StringArrayOutput)
}

func (o GetAddonReleasesResultOutput) OutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetAddonReleasesResult) *string { return v.OutputFile }).(pulumi.StringPtrOutput)
}

// A list of ARMS Addon Releases. Each element contains the following attributes:
func (o GetAddonReleasesResultOutput) Releases() GetAddonReleasesReleaseArrayOutput {
	return o.ApplyT(func(v GetAddonReleasesResult) []GetAddonReleasesRelease { return v.Releases }).(GetAddonReleasesReleaseArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetAddonReleasesResultOutput{})
}
