// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package arms

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-alicloud/sdk/v3/go/alicloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides the ARMS Env Service Monitors of the current Alibaba Cloud user.
//
// > **NOTE:** Available since v1.258.0.
func GetEnvServiceMonitors(ctx *pulumi.Context, args *GetEnvServiceMonitorsArgs, opts ...pulumi.InvokeOption) (*GetEnvServiceMonitorsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetEnvServiceMonitorsResult
	err := ctx.Invoke("alicloud:arms/getEnvServiceMonitors:getEnvServiceMonitors", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getEnvServiceMonitors.
type GetEnvServiceMonitorsArgs struct {
	// The environment ID.
	EnvironmentId string `pulumi:"environmentId"`
	// A list of ARMS Env Service Monitor IDs.
	Ids []string `pulumi:"ids"`
	// A regex string to filter results by ARMS Env Service Monitor name.
	NameRegex *string `pulumi:"nameRegex"`
	// File name where to save data source results (after running `pulumi preview`).
	OutputFile *string `pulumi:"outputFile"`
}

// A collection of values returned by getEnvServiceMonitors.
type GetEnvServiceMonitorsResult struct {
	// The environment ID.
	EnvironmentId string `pulumi:"environmentId"`
	// The provider-assigned unique ID for this managed resource.
	Id  string   `pulumi:"id"`
	Ids []string `pulumi:"ids"`
	// A list of ARMS Env Service Monitors. Each element contains the following attributes:
	Monitors  []GetEnvServiceMonitorsMonitor `pulumi:"monitors"`
	NameRegex *string                        `pulumi:"nameRegex"`
	// A list of ARMS Env Service Monitor names.
	Names      []string `pulumi:"names"`
	OutputFile *string  `pulumi:"outputFile"`
}

func GetEnvServiceMonitorsOutput(ctx *pulumi.Context, args GetEnvServiceMonitorsOutputArgs, opts ...pulumi.InvokeOption) GetEnvServiceMonitorsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetEnvServiceMonitorsResultOutput, error) {
			args := v.(GetEnvServiceMonitorsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("alicloud:arms/getEnvServiceMonitors:getEnvServiceMonitors", args, GetEnvServiceMonitorsResultOutput{}, options).(GetEnvServiceMonitorsResultOutput), nil
		}).(GetEnvServiceMonitorsResultOutput)
}

// A collection of arguments for invoking getEnvServiceMonitors.
type GetEnvServiceMonitorsOutputArgs struct {
	// The environment ID.
	EnvironmentId pulumi.StringInput `pulumi:"environmentId"`
	// A list of ARMS Env Service Monitor IDs.
	Ids pulumi.StringArrayInput `pulumi:"ids"`
	// A regex string to filter results by ARMS Env Service Monitor name.
	NameRegex pulumi.StringPtrInput `pulumi:"nameRegex"`
	// File name where to save data source results (after running `pulumi preview`).
	OutputFile pulumi.StringPtrInput `pulumi:"outputFile"`
}

func (GetEnvServiceMonitorsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEnvServiceMonitorsArgs)(nil)).Elem()
}

// A collection of values returned by getEnvServiceMonitors.
type GetEnvServiceMonitorsResultOutput struct{ *pulumi.OutputState }

func (GetEnvServiceMonitorsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEnvServiceMonitorsResult)(nil)).Elem()
}

func (o GetEnvServiceMonitorsResultOutput) ToGetEnvServiceMonitorsResultOutput() GetEnvServiceMonitorsResultOutput {
	return o
}

func (o GetEnvServiceMonitorsResultOutput) ToGetEnvServiceMonitorsResultOutputWithContext(ctx context.Context) GetEnvServiceMonitorsResultOutput {
	return o
}

// The environment ID.
func (o GetEnvServiceMonitorsResultOutput) EnvironmentId() pulumi.StringOutput {
	return o.ApplyT(func(v GetEnvServiceMonitorsResult) string { return v.EnvironmentId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetEnvServiceMonitorsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetEnvServiceMonitorsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetEnvServiceMonitorsResultOutput) Ids() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetEnvServiceMonitorsResult) []string { return v.Ids }).(pulumi.StringArrayOutput)
}

// A list of ARMS Env Service Monitors. Each element contains the following attributes:
func (o GetEnvServiceMonitorsResultOutput) Monitors() GetEnvServiceMonitorsMonitorArrayOutput {
	return o.ApplyT(func(v GetEnvServiceMonitorsResult) []GetEnvServiceMonitorsMonitor { return v.Monitors }).(GetEnvServiceMonitorsMonitorArrayOutput)
}

func (o GetEnvServiceMonitorsResultOutput) NameRegex() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetEnvServiceMonitorsResult) *string { return v.NameRegex }).(pulumi.StringPtrOutput)
}

// A list of ARMS Env Service Monitor names.
func (o GetEnvServiceMonitorsResultOutput) Names() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetEnvServiceMonitorsResult) []string { return v.Names }).(pulumi.StringArrayOutput)
}

func (o GetEnvServiceMonitorsResultOutput) OutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetEnvServiceMonitorsResult) *string { return v.OutputFile }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetEnvServiceMonitorsResultOutput{})
}
