// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package arms

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-alicloud/sdk/v3/go/alicloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides the ARMS Env Features of the current Alibaba Cloud user.
//
// > **NOTE:** Available since v1.258.0.
func GetEnvFeatures(ctx *pulumi.Context, args *GetEnvFeaturesArgs, opts ...pulumi.InvokeOption) (*GetEnvFeaturesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetEnvFeaturesResult
	err := ctx.Invoke("alicloud:arms/getEnvFeatures:getEnvFeatures", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getEnvFeatures.
type GetEnvFeaturesArgs struct {
	// The ID of the environment instance.
	EnvironmentId string `pulumi:"environmentId"`
	// A list of ARMS Env Feature IDs.
	Ids []string `pulumi:"ids"`
	// A regex string to filter results by ARMS Env Feature name.
	NameRegex *string `pulumi:"nameRegex"`
	// File name where to save data source results (after running `pulumi preview`).
	OutputFile *string `pulumi:"outputFile"`
}

// A collection of values returned by getEnvFeatures.
type GetEnvFeaturesResult struct {
	// The ID of the environment instance.
	EnvironmentId string `pulumi:"environmentId"`
	// A list of ARMS Env Features. Each element contains the following attributes:
	Features []GetEnvFeaturesFeature `pulumi:"features"`
	// The provider-assigned unique ID for this managed resource.
	Id        string   `pulumi:"id"`
	Ids       []string `pulumi:"ids"`
	NameRegex *string  `pulumi:"nameRegex"`
	// A list of ARMS Env Feature names.
	Names      []string `pulumi:"names"`
	OutputFile *string  `pulumi:"outputFile"`
}

func GetEnvFeaturesOutput(ctx *pulumi.Context, args GetEnvFeaturesOutputArgs, opts ...pulumi.InvokeOption) GetEnvFeaturesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetEnvFeaturesResultOutput, error) {
			args := v.(GetEnvFeaturesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("alicloud:arms/getEnvFeatures:getEnvFeatures", args, GetEnvFeaturesResultOutput{}, options).(GetEnvFeaturesResultOutput), nil
		}).(GetEnvFeaturesResultOutput)
}

// A collection of arguments for invoking getEnvFeatures.
type GetEnvFeaturesOutputArgs struct {
	// The ID of the environment instance.
	EnvironmentId pulumi.StringInput `pulumi:"environmentId"`
	// A list of ARMS Env Feature IDs.
	Ids pulumi.StringArrayInput `pulumi:"ids"`
	// A regex string to filter results by ARMS Env Feature name.
	NameRegex pulumi.StringPtrInput `pulumi:"nameRegex"`
	// File name where to save data source results (after running `pulumi preview`).
	OutputFile pulumi.StringPtrInput `pulumi:"outputFile"`
}

func (GetEnvFeaturesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEnvFeaturesArgs)(nil)).Elem()
}

// A collection of values returned by getEnvFeatures.
type GetEnvFeaturesResultOutput struct{ *pulumi.OutputState }

func (GetEnvFeaturesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEnvFeaturesResult)(nil)).Elem()
}

func (o GetEnvFeaturesResultOutput) ToGetEnvFeaturesResultOutput() GetEnvFeaturesResultOutput {
	return o
}

func (o GetEnvFeaturesResultOutput) ToGetEnvFeaturesResultOutputWithContext(ctx context.Context) GetEnvFeaturesResultOutput {
	return o
}

// The ID of the environment instance.
func (o GetEnvFeaturesResultOutput) EnvironmentId() pulumi.StringOutput {
	return o.ApplyT(func(v GetEnvFeaturesResult) string { return v.EnvironmentId }).(pulumi.StringOutput)
}

// A list of ARMS Env Features. Each element contains the following attributes:
func (o GetEnvFeaturesResultOutput) Features() GetEnvFeaturesFeatureArrayOutput {
	return o.ApplyT(func(v GetEnvFeaturesResult) []GetEnvFeaturesFeature { return v.Features }).(GetEnvFeaturesFeatureArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetEnvFeaturesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetEnvFeaturesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetEnvFeaturesResultOutput) Ids() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetEnvFeaturesResult) []string { return v.Ids }).(pulumi.StringArrayOutput)
}

func (o GetEnvFeaturesResultOutput) NameRegex() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetEnvFeaturesResult) *string { return v.NameRegex }).(pulumi.StringPtrOutput)
}

// A list of ARMS Env Feature names.
func (o GetEnvFeaturesResultOutput) Names() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetEnvFeaturesResult) []string { return v.Names }).(pulumi.StringArrayOutput)
}

func (o GetEnvFeaturesResultOutput) OutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetEnvFeaturesResult) *string { return v.OutputFile }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetEnvFeaturesResultOutput{})
}
