// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package arms

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-alicloud/sdk/v3/go/alicloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides the ARMS Env Pod Monitors of the current Alibaba Cloud user.
//
// > **NOTE:** Available since v1.258.0.
func GetEnvPodMonitors(ctx *pulumi.Context, args *GetEnvPodMonitorsArgs, opts ...pulumi.InvokeOption) (*GetEnvPodMonitorsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetEnvPodMonitorsResult
	err := ctx.Invoke("alicloud:arms/getEnvPodMonitors:getEnvPodMonitors", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getEnvPodMonitors.
type GetEnvPodMonitorsArgs struct {
	// The environment ID.
	EnvironmentId string `pulumi:"environmentId"`
	// A list of ARMS Env Pod Monitor IDs.
	Ids []string `pulumi:"ids"`
	// A regex string to filter results by ARMS Env Pod Monitor name.
	NameRegex *string `pulumi:"nameRegex"`
	// File name where to save data source results (after running `pulumi preview`).
	OutputFile *string `pulumi:"outputFile"`
}

// A collection of values returned by getEnvPodMonitors.
type GetEnvPodMonitorsResult struct {
	// The environment ID.
	EnvironmentId string `pulumi:"environmentId"`
	// The provider-assigned unique ID for this managed resource.
	Id  string   `pulumi:"id"`
	Ids []string `pulumi:"ids"`
	// A list of ARMS Env Pod Monitors. Each element contains the following attributes:
	Monitors  []GetEnvPodMonitorsMonitor `pulumi:"monitors"`
	NameRegex *string                    `pulumi:"nameRegex"`
	// A list of ARMS Env Pod Monitor names.
	Names      []string `pulumi:"names"`
	OutputFile *string  `pulumi:"outputFile"`
}

func GetEnvPodMonitorsOutput(ctx *pulumi.Context, args GetEnvPodMonitorsOutputArgs, opts ...pulumi.InvokeOption) GetEnvPodMonitorsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetEnvPodMonitorsResultOutput, error) {
			args := v.(GetEnvPodMonitorsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("alicloud:arms/getEnvPodMonitors:getEnvPodMonitors", args, GetEnvPodMonitorsResultOutput{}, options).(GetEnvPodMonitorsResultOutput), nil
		}).(GetEnvPodMonitorsResultOutput)
}

// A collection of arguments for invoking getEnvPodMonitors.
type GetEnvPodMonitorsOutputArgs struct {
	// The environment ID.
	EnvironmentId pulumi.StringInput `pulumi:"environmentId"`
	// A list of ARMS Env Pod Monitor IDs.
	Ids pulumi.StringArrayInput `pulumi:"ids"`
	// A regex string to filter results by ARMS Env Pod Monitor name.
	NameRegex pulumi.StringPtrInput `pulumi:"nameRegex"`
	// File name where to save data source results (after running `pulumi preview`).
	OutputFile pulumi.StringPtrInput `pulumi:"outputFile"`
}

func (GetEnvPodMonitorsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEnvPodMonitorsArgs)(nil)).Elem()
}

// A collection of values returned by getEnvPodMonitors.
type GetEnvPodMonitorsResultOutput struct{ *pulumi.OutputState }

func (GetEnvPodMonitorsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEnvPodMonitorsResult)(nil)).Elem()
}

func (o GetEnvPodMonitorsResultOutput) ToGetEnvPodMonitorsResultOutput() GetEnvPodMonitorsResultOutput {
	return o
}

func (o GetEnvPodMonitorsResultOutput) ToGetEnvPodMonitorsResultOutputWithContext(ctx context.Context) GetEnvPodMonitorsResultOutput {
	return o
}

// The environment ID.
func (o GetEnvPodMonitorsResultOutput) EnvironmentId() pulumi.StringOutput {
	return o.ApplyT(func(v GetEnvPodMonitorsResult) string { return v.EnvironmentId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetEnvPodMonitorsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetEnvPodMonitorsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetEnvPodMonitorsResultOutput) Ids() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetEnvPodMonitorsResult) []string { return v.Ids }).(pulumi.StringArrayOutput)
}

// A list of ARMS Env Pod Monitors. Each element contains the following attributes:
func (o GetEnvPodMonitorsResultOutput) Monitors() GetEnvPodMonitorsMonitorArrayOutput {
	return o.ApplyT(func(v GetEnvPodMonitorsResult) []GetEnvPodMonitorsMonitor { return v.Monitors }).(GetEnvPodMonitorsMonitorArrayOutput)
}

func (o GetEnvPodMonitorsResultOutput) NameRegex() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetEnvPodMonitorsResult) *string { return v.NameRegex }).(pulumi.StringPtrOutput)
}

// A list of ARMS Env Pod Monitor names.
func (o GetEnvPodMonitorsResultOutput) Names() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetEnvPodMonitorsResult) []string { return v.Names }).(pulumi.StringArrayOutput)
}

func (o GetEnvPodMonitorsResultOutput) OutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetEnvPodMonitorsResult) *string { return v.OutputFile }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetEnvPodMonitorsResultOutput{})
}
