// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AliCloud.Arms
{
    public static class GetAddonReleases
    {
        /// <summary>
        /// This data source provides the ARMS Addon Releases of the current Alibaba Cloud user.
        /// 
        /// &gt; **NOTE:** Available since v1.258.0.
        /// </summary>
        public static Task<GetAddonReleasesResult> InvokeAsync(GetAddonReleasesArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAddonReleasesResult>("alicloud:arms/getAddonReleases:getAddonReleases", args ?? new GetAddonReleasesArgs(), options.WithDefaults());

        /// <summary>
        /// This data source provides the ARMS Addon Releases of the current Alibaba Cloud user.
        /// 
        /// &gt; **NOTE:** Available since v1.258.0.
        /// </summary>
        public static Output<GetAddonReleasesResult> Invoke(GetAddonReleasesInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAddonReleasesResult>("alicloud:arms/getAddonReleases:getAddonReleases", args ?? new GetAddonReleasesInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// This data source provides the ARMS Addon Releases of the current Alibaba Cloud user.
        /// 
        /// &gt; **NOTE:** Available since v1.258.0.
        /// </summary>
        public static Output<GetAddonReleasesResult> Invoke(GetAddonReleasesInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetAddonReleasesResult>("alicloud:arms/getAddonReleases:getAddonReleases", args ?? new GetAddonReleasesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetAddonReleasesArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The environment ID.
        /// </summary>
        [Input("environmentId", required: true)]
        public string EnvironmentId { get; set; } = null!;

        [Input("ids")]
        private List<string>? _ids;

        /// <summary>
        /// A list of ARMS Addon Release IDs.
        /// </summary>
        public List<string> Ids
        {
            get => _ids ?? (_ids = new List<string>());
            set => _ids = value;
        }

        /// <summary>
        /// A regex string to filter results by ARMS Addon Release name.
        /// </summary>
        [Input("nameRegex")]
        public string? NameRegex { get; set; }

        /// <summary>
        /// File name where to save data source results (after running `pulumi preview`).
        /// </summary>
        [Input("outputFile")]
        public string? OutputFile { get; set; }

        public GetAddonReleasesArgs()
        {
        }
        public static new GetAddonReleasesArgs Empty => new GetAddonReleasesArgs();
    }

    public sealed class GetAddonReleasesInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The environment ID.
        /// </summary>
        [Input("environmentId", required: true)]
        public Input<string> EnvironmentId { get; set; } = null!;

        [Input("ids")]
        private InputList<string>? _ids;

        /// <summary>
        /// A list of ARMS Addon Release IDs.
        /// </summary>
        public InputList<string> Ids
        {
            get => _ids ?? (_ids = new InputList<string>());
            set => _ids = value;
        }

        /// <summary>
        /// A regex string to filter results by ARMS Addon Release name.
        /// </summary>
        [Input("nameRegex")]
        public Input<string>? NameRegex { get; set; }

        /// <summary>
        /// File name where to save data source results (after running `pulumi preview`).
        /// </summary>
        [Input("outputFile")]
        public Input<string>? OutputFile { get; set; }

        public GetAddonReleasesInvokeArgs()
        {
        }
        public static new GetAddonReleasesInvokeArgs Empty => new GetAddonReleasesInvokeArgs();
    }


    [OutputType]
    public sealed class GetAddonReleasesResult
    {
        /// <summary>
        /// The environment ID.
        /// </summary>
        public readonly string EnvironmentId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<string> Ids;
        public readonly string? NameRegex;
        /// <summary>
        /// A list of ARMS Addon Release names.
        /// </summary>
        public readonly ImmutableArray<string> Names;
        public readonly string? OutputFile;
        /// <summary>
        /// A list of ARMS Addon Releases. Each element contains the following attributes:
        /// </summary>
        public readonly ImmutableArray<Outputs.GetAddonReleasesReleaseResult> Releases;

        [OutputConstructor]
        private GetAddonReleasesResult(
            string environmentId,

            string id,

            ImmutableArray<string> ids,

            string? nameRegex,

            ImmutableArray<string> names,

            string? outputFile,

            ImmutableArray<Outputs.GetAddonReleasesReleaseResult> releases)
        {
            EnvironmentId = environmentId;
            Id = id;
            Ids = ids;
            NameRegex = nameRegex;
            Names = names;
            OutputFile = outputFile;
            Releases = releases;
        }
    }
}
