// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AliCloud.Arms
{
    public static class GetEnvServiceMonitors
    {
        /// <summary>
        /// This data source provides the ARMS Env Service Monitors of the current Alibaba Cloud user.
        /// 
        /// &gt; **NOTE:** Available since v1.258.0.
        /// </summary>
        public static Task<GetEnvServiceMonitorsResult> InvokeAsync(GetEnvServiceMonitorsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetEnvServiceMonitorsResult>("alicloud:arms/getEnvServiceMonitors:getEnvServiceMonitors", args ?? new GetEnvServiceMonitorsArgs(), options.WithDefaults());

        /// <summary>
        /// This data source provides the ARMS Env Service Monitors of the current Alibaba Cloud user.
        /// 
        /// &gt; **NOTE:** Available since v1.258.0.
        /// </summary>
        public static Output<GetEnvServiceMonitorsResult> Invoke(GetEnvServiceMonitorsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetEnvServiceMonitorsResult>("alicloud:arms/getEnvServiceMonitors:getEnvServiceMonitors", args ?? new GetEnvServiceMonitorsInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// This data source provides the ARMS Env Service Monitors of the current Alibaba Cloud user.
        /// 
        /// &gt; **NOTE:** Available since v1.258.0.
        /// </summary>
        public static Output<GetEnvServiceMonitorsResult> Invoke(GetEnvServiceMonitorsInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetEnvServiceMonitorsResult>("alicloud:arms/getEnvServiceMonitors:getEnvServiceMonitors", args ?? new GetEnvServiceMonitorsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetEnvServiceMonitorsArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The environment ID.
        /// </summary>
        [Input("environmentId", required: true)]
        public string EnvironmentId { get; set; } = null!;

        [Input("ids")]
        private List<string>? _ids;

        /// <summary>
        /// A list of ARMS Env Service Monitor IDs.
        /// </summary>
        public List<string> Ids
        {
            get => _ids ?? (_ids = new List<string>());
            set => _ids = value;
        }

        /// <summary>
        /// A regex string to filter results by ARMS Env Service Monitor name.
        /// </summary>
        [Input("nameRegex")]
        public string? NameRegex { get; set; }

        /// <summary>
        /// File name where to save data source results (after running `pulumi preview`).
        /// </summary>
        [Input("outputFile")]
        public string? OutputFile { get; set; }

        public GetEnvServiceMonitorsArgs()
        {
        }
        public static new GetEnvServiceMonitorsArgs Empty => new GetEnvServiceMonitorsArgs();
    }

    public sealed class GetEnvServiceMonitorsInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The environment ID.
        /// </summary>
        [Input("environmentId", required: true)]
        public Input<string> EnvironmentId { get; set; } = null!;

        [Input("ids")]
        private InputList<string>? _ids;

        /// <summary>
        /// A list of ARMS Env Service Monitor IDs.
        /// </summary>
        public InputList<string> Ids
        {
            get => _ids ?? (_ids = new InputList<string>());
            set => _ids = value;
        }

        /// <summary>
        /// A regex string to filter results by ARMS Env Service Monitor name.
        /// </summary>
        [Input("nameRegex")]
        public Input<string>? NameRegex { get; set; }

        /// <summary>
        /// File name where to save data source results (after running `pulumi preview`).
        /// </summary>
        [Input("outputFile")]
        public Input<string>? OutputFile { get; set; }

        public GetEnvServiceMonitorsInvokeArgs()
        {
        }
        public static new GetEnvServiceMonitorsInvokeArgs Empty => new GetEnvServiceMonitorsInvokeArgs();
    }


    [OutputType]
    public sealed class GetEnvServiceMonitorsResult
    {
        /// <summary>
        /// The environment ID.
        /// </summary>
        public readonly string EnvironmentId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<string> Ids;
        /// <summary>
        /// A list of ARMS Env Service Monitors. Each element contains the following attributes:
        /// </summary>
        public readonly ImmutableArray<Outputs.GetEnvServiceMonitorsMonitorResult> Monitors;
        public readonly string? NameRegex;
        /// <summary>
        /// A list of ARMS Env Service Monitor names.
        /// </summary>
        public readonly ImmutableArray<string> Names;
        public readonly string? OutputFile;

        [OutputConstructor]
        private GetEnvServiceMonitorsResult(
            string environmentId,

            string id,

            ImmutableArray<string> ids,

            ImmutableArray<Outputs.GetEnvServiceMonitorsMonitorResult> monitors,

            string? nameRegex,

            ImmutableArray<string> names,

            string? outputFile)
        {
            EnvironmentId = environmentId;
            Id = id;
            Ids = ids;
            Monitors = monitors;
            NameRegex = nameRegex;
            Names = names;
            OutputFile = outputFile;
        }
    }
}
