// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AliCloud.Arms
{
    public static class GetEnvFeatures
    {
        /// <summary>
        /// This data source provides the ARMS Env Features of the current Alibaba Cloud user.
        /// 
        /// &gt; **NOTE:** Available since v1.258.0.
        /// </summary>
        public static Task<GetEnvFeaturesResult> InvokeAsync(GetEnvFeaturesArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetEnvFeaturesResult>("alicloud:arms/getEnvFeatures:getEnvFeatures", args ?? new GetEnvFeaturesArgs(), options.WithDefaults());

        /// <summary>
        /// This data source provides the ARMS Env Features of the current Alibaba Cloud user.
        /// 
        /// &gt; **NOTE:** Available since v1.258.0.
        /// </summary>
        public static Output<GetEnvFeaturesResult> Invoke(GetEnvFeaturesInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetEnvFeaturesResult>("alicloud:arms/getEnvFeatures:getEnvFeatures", args ?? new GetEnvFeaturesInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// This data source provides the ARMS Env Features of the current Alibaba Cloud user.
        /// 
        /// &gt; **NOTE:** Available since v1.258.0.
        /// </summary>
        public static Output<GetEnvFeaturesResult> Invoke(GetEnvFeaturesInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetEnvFeaturesResult>("alicloud:arms/getEnvFeatures:getEnvFeatures", args ?? new GetEnvFeaturesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetEnvFeaturesArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the environment instance.
        /// </summary>
        [Input("environmentId", required: true)]
        public string EnvironmentId { get; set; } = null!;

        [Input("ids")]
        private List<string>? _ids;

        /// <summary>
        /// A list of ARMS Env Feature IDs.
        /// </summary>
        public List<string> Ids
        {
            get => _ids ?? (_ids = new List<string>());
            set => _ids = value;
        }

        /// <summary>
        /// A regex string to filter results by ARMS Env Feature name.
        /// </summary>
        [Input("nameRegex")]
        public string? NameRegex { get; set; }

        /// <summary>
        /// File name where to save data source results (after running `pulumi preview`).
        /// </summary>
        [Input("outputFile")]
        public string? OutputFile { get; set; }

        public GetEnvFeaturesArgs()
        {
        }
        public static new GetEnvFeaturesArgs Empty => new GetEnvFeaturesArgs();
    }

    public sealed class GetEnvFeaturesInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the environment instance.
        /// </summary>
        [Input("environmentId", required: true)]
        public Input<string> EnvironmentId { get; set; } = null!;

        [Input("ids")]
        private InputList<string>? _ids;

        /// <summary>
        /// A list of ARMS Env Feature IDs.
        /// </summary>
        public InputList<string> Ids
        {
            get => _ids ?? (_ids = new InputList<string>());
            set => _ids = value;
        }

        /// <summary>
        /// A regex string to filter results by ARMS Env Feature name.
        /// </summary>
        [Input("nameRegex")]
        public Input<string>? NameRegex { get; set; }

        /// <summary>
        /// File name where to save data source results (after running `pulumi preview`).
        /// </summary>
        [Input("outputFile")]
        public Input<string>? OutputFile { get; set; }

        public GetEnvFeaturesInvokeArgs()
        {
        }
        public static new GetEnvFeaturesInvokeArgs Empty => new GetEnvFeaturesInvokeArgs();
    }


    [OutputType]
    public sealed class GetEnvFeaturesResult
    {
        /// <summary>
        /// The ID of the environment instance.
        /// </summary>
        public readonly string EnvironmentId;
        /// <summary>
        /// A list of ARMS Env Features. Each element contains the following attributes:
        /// </summary>
        public readonly ImmutableArray<Outputs.GetEnvFeaturesFeatureResult> Features;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<string> Ids;
        public readonly string? NameRegex;
        /// <summary>
        /// A list of ARMS Env Feature names.
        /// </summary>
        public readonly ImmutableArray<string> Names;
        public readonly string? OutputFile;

        [OutputConstructor]
        private GetEnvFeaturesResult(
            string environmentId,

            ImmutableArray<Outputs.GetEnvFeaturesFeatureResult> features,

            string id,

            ImmutableArray<string> ids,

            string? nameRegex,

            ImmutableArray<string> names,

            string? outputFile)
        {
            EnvironmentId = environmentId;
            Features = features;
            Id = id;
            Ids = ids;
            NameRegex = nameRegex;
            Names = names;
            OutputFile = outputFile;
        }
    }
}
