// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.alicloud.ess;

import com.pulumi.alicloud.Utilities;
import com.pulumi.alicloud.ess.AlarmArgs;
import com.pulumi.alicloud.ess.inputs.AlarmState;
import com.pulumi.alicloud.ess.outputs.AlarmExpression;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Provides a ESS alarm task resource.
 * 
 * For information about ess alarm, see [CreateAlarm](https://www.alibabacloud.com/help/en/auto-scaling/latest/createalarm).
 * 
 * &gt; **NOTE:** Available since v1.15.0.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Module Support
 * 
 * You can use to the existing autoscaling-rule module
 * to create alarm task, different type rules and scheduled task one-click.
 * 
 * ## Import
 * 
 * Ess alarm can be imported using the id, e.g.
 * 
 * ```sh
 * $ pulumi import alicloud:ess/alarm:Alarm example asg-2ze500_045efffe-4d05
 * ```
 * 
 */
@ResourceType(type="alicloud:ess/alarm:Alarm")
public class Alarm extends com.pulumi.resources.CustomResource {
    /**
     * The list of actions to execute when this alarm transition into an ALARM state. Each action is specified as ess scaling rule ari.
     * 
     */
    @Export(name="alarmActions", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> alarmActions;

    /**
     * @return The list of actions to execute when this alarm transition into an ALARM state. Each action is specified as ess scaling rule ari.
     * 
     */
    public Output<List<String>> alarmActions() {
        return this.alarmActions;
    }
    /**
     * Defines the application group id defined by CMS which is assigned when you upload custom metric to CMS, only available for custom metirc.
     * 
     */
    @Export(name="cloudMonitorGroupId", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> cloudMonitorGroupId;

    /**
     * @return Defines the application group id defined by CMS which is assigned when you upload custom metric to CMS, only available for custom metirc.
     * 
     */
    public Output<Optional<Integer>> cloudMonitorGroupId() {
        return Codegen.optional(this.cloudMonitorGroupId);
    }
    /**
     * The arithmetic operation to use when comparing the specified Statistic and Threshold. The specified Statistic value is used as the first operand. Supported value: &gt;=, &lt;=, &gt;, &lt;. Defaults to &gt;=.
     * 
     */
    @Export(name="comparisonOperator", refs={String.class}, tree="[0]")
    private Output<String> comparisonOperator;

    /**
     * @return The arithmetic operation to use when comparing the specified Statistic and Threshold. The specified Statistic value is used as the first operand. Supported value: &gt;=, &lt;=, &gt;, &lt;. Defaults to &gt;=.
     * 
     */
    public Output<String> comparisonOperator() {
        return this.comparisonOperator;
    }
    /**
     * The description for the alarm.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return The description for the alarm.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * The dimension map for the alarm&#39;s associated metric. For all metrics, you can not set the dimension key as &#34;scaling_group&#34; or &#34;userId&#34;, which is set by default, the second dimension for metric, such as &#34;device&#34; for &#34;PackagesNetIn&#34;, need to be set by users. See `dimensions` below.
     * 
     */
    @Export(name="dimensions", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output<Map<String,String>> dimensions;

    /**
     * @return The dimension map for the alarm&#39;s associated metric. For all metrics, you can not set the dimension key as &#34;scaling_group&#34; or &#34;userId&#34;, which is set by default, the second dimension for metric, such as &#34;device&#34; for &#34;PackagesNetIn&#34;, need to be set by users. See `dimensions` below.
     * 
     */
    public Output<Map<String,String>> dimensions() {
        return this.dimensions;
    }
    /**
     * Whether to enable specific ess alarm. Default to true.
     * 
     */
    @Export(name="enable", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> enable;

    /**
     * @return Whether to enable specific ess alarm. Default to true.
     * 
     */
    public Output<Optional<Boolean>> enable() {
        return Codegen.optional(this.enable);
    }
    /**
     * The number of times that needs to satisfies comparison condition before transition into ALARM state. Defaults to 3.
     * 
     */
    @Export(name="evaluationCount", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> evaluationCount;

    /**
     * @return The number of times that needs to satisfies comparison condition before transition into ALARM state. Defaults to 3.
     * 
     */
    public Output<Optional<Integer>> evaluationCount() {
        return Codegen.optional(this.evaluationCount);
    }
    /**
     * Support multi alert rule. See `expressions` below for details.
     * 
     */
    @Export(name="expressions", refs={List.class,AlarmExpression.class}, tree="[0,1]")
    private Output<List<AlarmExpression>> expressions;

    /**
     * @return Support multi alert rule. See `expressions` below for details.
     * 
     */
    public Output<List<AlarmExpression>> expressions() {
        return this.expressions;
    }
    /**
     * The relationship between the trigger conditions in the multi-metric alert rule.
     * 
     */
    @Export(name="expressionsLogicOperator", refs={String.class}, tree="[0]")
    private Output<String> expressionsLogicOperator;

    /**
     * @return The relationship between the trigger conditions in the multi-metric alert rule.
     * 
     */
    public Output<String> expressionsLogicOperator() {
        return this.expressionsLogicOperator;
    }
    /**
     * The name for the alarm&#39;s associated metric. See `dimensions` below for details.
     * 
     */
    @Export(name="metricName", refs={String.class}, tree="[0]")
    private Output<String> metricName;

    /**
     * @return The name for the alarm&#39;s associated metric. See `dimensions` below for details.
     * 
     */
    public Output<String> metricName() {
        return this.metricName;
    }
    /**
     * The type for the alarm&#39;s associated metric. Supported value: system, custom. &#34;system&#34; means the metric data is collected by Aliyun Cloud Monitor Service(CMS), &#34;custom&#34; means the metric data is upload to CMS by users. Defaults to system.
     * 
     */
    @Export(name="metricType", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> metricType;

    /**
     * @return The type for the alarm&#39;s associated metric. Supported value: system, custom. &#34;system&#34; means the metric data is collected by Aliyun Cloud Monitor Service(CMS), &#34;custom&#34; means the metric data is upload to CMS by users. Defaults to system.
     * 
     */
    public Output<Optional<String>> metricType() {
        return Codegen.optional(this.metricType);
    }
    /**
     * The name for ess alarm.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name for ess alarm.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The period in seconds over which the specified statistic is applied. Supported value: 60, 120, 300, 900. Defaults to 300.
     * 
     */
    @Export(name="period", refs={Integer.class}, tree="[0]")
    private Output<Integer> period;

    /**
     * @return The period in seconds over which the specified statistic is applied. Supported value: 60, 120, 300, 900. Defaults to 300.
     * 
     */
    public Output<Integer> period() {
        return this.period;
    }
    /**
     * The scaling group associated with this alarm, the &#39;ForceNew&#39; attribute is available in 1.56.0+.
     * 
     */
    @Export(name="scalingGroupId", refs={String.class}, tree="[0]")
    private Output<String> scalingGroupId;

    /**
     * @return The scaling group associated with this alarm, the &#39;ForceNew&#39; attribute is available in 1.56.0+.
     * 
     */
    public Output<String> scalingGroupId() {
        return this.scalingGroupId;
    }
    /**
     * The status of the event-triggered task. Valid values:
     * - ALARM: The alert condition is met and an alert is triggered.
     * - OK: The alert condition is not met.
     * - INSUFFICIENT_DATA: Auto Scaling cannot determine whether the alert condition is met due to insufficient data.
     * 
     */
    @Export(name="state", refs={String.class}, tree="[0]")
    private Output<String> state;

    /**
     * @return The status of the event-triggered task. Valid values:
     * - ALARM: The alert condition is met and an alert is triggered.
     * - OK: The alert condition is not met.
     * - INSUFFICIENT_DATA: Auto Scaling cannot determine whether the alert condition is met due to insufficient data.
     * 
     */
    public Output<String> state() {
        return this.state;
    }
    /**
     * The statistic to apply to the alarm&#39;s associated metric. Supported value: Average, Minimum, Maximum. Defaults to Average.
     * 
     */
    @Export(name="statistics", refs={String.class}, tree="[0]")
    private Output<String> statistics;

    /**
     * @return The statistic to apply to the alarm&#39;s associated metric. Supported value: Average, Minimum, Maximum. Defaults to Average.
     * 
     */
    public Output<String> statistics() {
        return this.statistics;
    }
    /**
     * The value against which the specified statistics is compared.
     * 
     */
    @Export(name="threshold", refs={String.class}, tree="[0]")
    private Output<String> threshold;

    /**
     * @return The value against which the specified statistics is compared.
     * 
     */
    public Output<String> threshold() {
        return this.threshold;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Alarm(java.lang.String name) {
        this(name, AlarmArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Alarm(java.lang.String name, AlarmArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Alarm(java.lang.String name, AlarmArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("alicloud:ess/alarm:Alarm", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Alarm(java.lang.String name, Output<java.lang.String> id, @Nullable AlarmState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("alicloud:ess/alarm:Alarm", name, state, makeResourceOptions(options, id), false);
    }

    private static AlarmArgs makeArgs(AlarmArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? AlarmArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Alarm get(java.lang.String name, Output<java.lang.String> id, @Nullable AlarmState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Alarm(name, id, state, options);
    }
}
