// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.alicloud.ess;

import com.pulumi.alicloud.Utilities;
import com.pulumi.alicloud.ess.AttachmentArgs;
import com.pulumi.alicloud.ess.inputs.AttachmentState;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Attaches several ECS instances to a specified scaling group or remove them from it.
 * 
 * &gt; **NOTE:** ECS instances can be attached or remove only when the scaling group is active, and it has no scaling activity in progress.
 * 
 * &gt; **NOTE:** There are two types ECS instances in a scaling group: &#34;AutoCreated&#34; and &#34;Attached&#34;. The total number of them can not larger than the scaling group &#34;MaxSize&#34;.
 * 
 * &gt; **NOTE:** Available since v1.6.0.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Import
 * 
 * ESS attachment can be imported using the id or scaling group id, e.g.
 * 
 * ```sh
 * $ pulumi import alicloud:ess/attachment:Attachment example asg-abc123456
 * ```
 * 
 */
@ResourceType(type="alicloud:ess/attachment:Attachment")
public class Attachment extends com.pulumi.resources.CustomResource {
    /**
     * Specifies whether the scaling group manages the lifecycles of the instances that are manually added to the scaling group.
     * 
     */
    @Export(name="entrusted", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> entrusted;

    /**
     * @return Specifies whether the scaling group manages the lifecycles of the instances that are manually added to the scaling group.
     * 
     */
    public Output<Optional<Boolean>> entrusted() {
        return Codegen.optional(this.entrusted);
    }
    /**
     * Whether to remove forcibly &#34;AutoCreated&#34; ECS instances in order to release scaling group capacity &#34;MaxSize&#34; for attaching ECS instances. Default to false.
     * 
     */
    @Export(name="force", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> force;

    /**
     * @return Whether to remove forcibly &#34;AutoCreated&#34; ECS instances in order to release scaling group capacity &#34;MaxSize&#34; for attaching ECS instances. Default to false.
     * 
     */
    public Output<Optional<Boolean>> force() {
        return Codegen.optional(this.force);
    }
    /**
     * ID of the ECS instance to be attached to the scaling group. You can input up to 20 IDs.
     * 
     */
    @Export(name="instanceIds", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> instanceIds;

    /**
     * @return ID of the ECS instance to be attached to the scaling group. You can input up to 20 IDs.
     * 
     */
    public Output<List<String>> instanceIds() {
        return this.instanceIds;
    }
    /**
     * Specifies whether to trigger a lifecycle hook for the scaling group to which instances are being added.
     * 
     */
    @Export(name="lifecycleHook", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> lifecycleHook;

    /**
     * @return Specifies whether to trigger a lifecycle hook for the scaling group to which instances are being added.
     * 
     */
    public Output<Optional<Boolean>> lifecycleHook() {
        return Codegen.optional(this.lifecycleHook);
    }
    /**
     * The weight of ECS instance N or elastic container instance N as a backend server of the associated Server Load Balancer (SLB) instance. Valid values of N: 1 to 20. Valid values of this parameter: 1 to 100.
     * 
     * &gt; **NOTE:** &#34;AutoCreated&#34; ECS instance will be deleted after it is removed from scaling group, but &#34;Attached&#34; will be not.
     * 
     * &gt; **NOTE:** Restrictions on attaching ECS instances:
     * 
     * - The attached ECS instances and the scaling group must have the same region and network type(`Classic` or `VPC`).
     * - The attached ECS instances and the instance with active scaling configurations must have the same instance type.
     * - The attached ECS instances must in the running state.
     * - The attached ECS instances has not been attached to other scaling groups.
     * - The attached ECS instances supports Subscription and Pay-As-You-Go payment methods.
     * 
     */
    @Export(name="loadBalancerWeights", refs={List.class,Integer.class}, tree="[0,1]")
    private Output<List<Integer>> loadBalancerWeights;

    /**
     * @return The weight of ECS instance N or elastic container instance N as a backend server of the associated Server Load Balancer (SLB) instance. Valid values of N: 1 to 20. Valid values of this parameter: 1 to 100.
     * 
     * &gt; **NOTE:** &#34;AutoCreated&#34; ECS instance will be deleted after it is removed from scaling group, but &#34;Attached&#34; will be not.
     * 
     * &gt; **NOTE:** Restrictions on attaching ECS instances:
     * 
     * - The attached ECS instances and the scaling group must have the same region and network type(`Classic` or `VPC`).
     * - The attached ECS instances and the instance with active scaling configurations must have the same instance type.
     * - The attached ECS instances must in the running state.
     * - The attached ECS instances has not been attached to other scaling groups.
     * - The attached ECS instances supports Subscription and Pay-As-You-Go payment methods.
     * 
     */
    public Output<List<Integer>> loadBalancerWeights() {
        return this.loadBalancerWeights;
    }
    /**
     * ID of the scaling group of a scaling configuration.
     * 
     */
    @Export(name="scalingGroupId", refs={String.class}, tree="[0]")
    private Output<String> scalingGroupId;

    /**
     * @return ID of the scaling group of a scaling configuration.
     * 
     */
    public Output<String> scalingGroupId() {
        return this.scalingGroupId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Attachment(java.lang.String name) {
        this(name, AttachmentArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Attachment(java.lang.String name, AttachmentArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Attachment(java.lang.String name, AttachmentArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("alicloud:ess/attachment:Attachment", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Attachment(java.lang.String name, Output<java.lang.String> id, @Nullable AttachmentState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("alicloud:ess/attachment:Attachment", name, state, makeResourceOptions(options, id), false);
    }

    private static AttachmentArgs makeArgs(AttachmentArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? AttachmentArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Attachment get(java.lang.String name, Output<java.lang.String> id, @Nullable AttachmentState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Attachment(name, id, state, options);
    }
}
