// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.alicloud.message;

import com.pulumi.alicloud.Utilities;
import com.pulumi.alicloud.message.ServiceEventRuleArgs;
import com.pulumi.alicloud.message.inputs.ServiceEventRuleState;
import com.pulumi.alicloud.message.outputs.ServiceEventRuleEndpoint;
import com.pulumi.alicloud.message.outputs.ServiceEventRuleMatchRule;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Provides a Message Service Event Rule resource.
 * 
 * For information about Message Service Event Rule and how to use it, see [What is Event Rule](https://next.api.alibabacloud.com/document/Mns-open/2022-01-19/CreateEventRule).
 * 
 * &gt; **NOTE:** Available since v1.255.0.
 * 
 * ## Import
 * 
 * Message Service Event Rule can be imported using the id, e.g.
 * 
 * ```sh
 * $ pulumi import alicloud:message/serviceEventRule:ServiceEventRule example &lt;id&gt;
 * ```
 * 
 */
@ResourceType(type="alicloud:message/serviceEventRule:ServiceEventRule")
public class ServiceEventRule extends com.pulumi.resources.CustomResource {
    /**
     * DIRECT: directly delivers to a single queue (1:1) without creating a Topic;
     * - BROADCAST: BROADCAST to all subscription queues (1:N). You need to create a Topic;
     * 
     */
    @Export(name="deliveryMode", refs={String.class}, tree="[0]")
    private Output<String> deliveryMode;

    /**
     * @return DIRECT: directly delivers to a single queue (1:1) without creating a Topic;
     * - BROADCAST: BROADCAST to all subscription queues (1:N). You need to create a Topic;
     * 
     */
    public Output<String> deliveryMode() {
        return this.deliveryMode;
    }
    /**
     * Message Receiving Terminal Endpoint Object. See `endpoint` below.
     * 
     */
    @Export(name="endpoint", refs={ServiceEventRuleEndpoint.class}, tree="[0]")
    private Output</* @Nullable */ ServiceEventRuleEndpoint> endpoint;

    /**
     * @return Message Receiving Terminal Endpoint Object. See `endpoint` below.
     * 
     */
    public Output<Optional<ServiceEventRuleEndpoint>> endpoint() {
        return Codegen.optional(this.endpoint);
    }
    /**
     * Event Type List
     * 
     */
    @Export(name="eventTypes", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> eventTypes;

    /**
     * @return Event Type List
     * 
     */
    public Output<List<String>> eventTypes() {
        return this.eventTypes;
    }
    /**
     * Matching rules, or relationships between multiple rules. See `match_rules` below.
     * 
     */
    @Export(name="matchRules", refs={List.class,ServiceEventRuleMatchRule.class}, tree="[0,[0,1]]")
    private Output</* @Nullable */ List<List<ServiceEventRuleMatchRule>>> matchRules;

    /**
     * @return Matching rules, or relationships between multiple rules. See `match_rules` below.
     * 
     */
    public Output<Optional<List<List<ServiceEventRuleMatchRule>>>> matchRules() {
        return Codegen.optional(this.matchRules);
    }
    /**
     * The event notification rule name.
     * 
     */
    @Export(name="ruleName", refs={String.class}, tree="[0]")
    private Output<String> ruleName;

    /**
     * @return The event notification rule name.
     * 
     */
    public Output<String> ruleName() {
        return this.ruleName;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ServiceEventRule(java.lang.String name) {
        this(name, ServiceEventRuleArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ServiceEventRule(java.lang.String name, ServiceEventRuleArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ServiceEventRule(java.lang.String name, ServiceEventRuleArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("alicloud:message/serviceEventRule:ServiceEventRule", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private ServiceEventRule(java.lang.String name, Output<java.lang.String> id, @Nullable ServiceEventRuleState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("alicloud:message/serviceEventRule:ServiceEventRule", name, state, makeResourceOptions(options, id), false);
    }

    private static ServiceEventRuleArgs makeArgs(ServiceEventRuleArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ServiceEventRuleArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/zhangyoufu/pulumi-alicloud")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ServiceEventRule get(java.lang.String name, Output<java.lang.String> id, @Nullable ServiceEventRuleState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ServiceEventRule(name, id, state, options);
    }
}
