// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * This data source provides the ARMS Addon Releases of the current Alibaba Cloud user.
 *
 * > **NOTE:** Available since v1.258.0.
 */
export function getAddonReleases(args: GetAddonReleasesArgs, opts?: pulumi.InvokeOptions): Promise<GetAddonReleasesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("alicloud:arms/getAddonReleases:getAddonReleases", {
        "environmentId": args.environmentId,
        "ids": args.ids,
        "nameRegex": args.nameRegex,
        "outputFile": args.outputFile,
    }, opts);
}

/**
 * A collection of arguments for invoking getAddonReleases.
 */
export interface GetAddonReleasesArgs {
    /**
     * The environment ID.
     */
    environmentId: string;
    /**
     * A list of ARMS Addon Release IDs.
     */
    ids?: string[];
    /**
     * A regex string to filter results by ARMS Addon Release name.
     */
    nameRegex?: string;
    /**
     * File name where to save data source results (after running `pulumi preview`).
     */
    outputFile?: string;
}

/**
 * A collection of values returned by getAddonReleases.
 */
export interface GetAddonReleasesResult {
    /**
     * The environment ID.
     */
    readonly environmentId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly ids: string[];
    readonly nameRegex?: string;
    /**
     * A list of ARMS Addon Release names.
     */
    readonly names: string[];
    readonly outputFile?: string;
    /**
     * A list of ARMS Addon Releases. Each element contains the following attributes:
     */
    readonly releases: outputs.arms.GetAddonReleasesRelease[];
}
/**
 * This data source provides the ARMS Addon Releases of the current Alibaba Cloud user.
 *
 * > **NOTE:** Available since v1.258.0.
 */
export function getAddonReleasesOutput(args: GetAddonReleasesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAddonReleasesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("alicloud:arms/getAddonReleases:getAddonReleases", {
        "environmentId": args.environmentId,
        "ids": args.ids,
        "nameRegex": args.nameRegex,
        "outputFile": args.outputFile,
    }, opts);
}

/**
 * A collection of arguments for invoking getAddonReleases.
 */
export interface GetAddonReleasesOutputArgs {
    /**
     * The environment ID.
     */
    environmentId: pulumi.Input<string>;
    /**
     * A list of ARMS Addon Release IDs.
     */
    ids?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A regex string to filter results by ARMS Addon Release name.
     */
    nameRegex?: pulumi.Input<string>;
    /**
     * File name where to save data source results (after running `pulumi preview`).
     */
    outputFile?: pulumi.Input<string>;
}
