// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * This data source provides the ARMS Env Pod Monitors of the current Alibaba Cloud user.
 *
 * > **NOTE:** Available since v1.258.0.
 */
export function getEnvPodMonitors(args: GetEnvPodMonitorsArgs, opts?: pulumi.InvokeOptions): Promise<GetEnvPodMonitorsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("alicloud:arms/getEnvPodMonitors:getEnvPodMonitors", {
        "environmentId": args.environmentId,
        "ids": args.ids,
        "nameRegex": args.nameRegex,
        "outputFile": args.outputFile,
    }, opts);
}

/**
 * A collection of arguments for invoking getEnvPodMonitors.
 */
export interface GetEnvPodMonitorsArgs {
    /**
     * The environment ID.
     */
    environmentId: string;
    /**
     * A list of ARMS Env Pod Monitor IDs.
     */
    ids?: string[];
    /**
     * A regex string to filter results by ARMS Env Pod Monitor name.
     */
    nameRegex?: string;
    /**
     * File name where to save data source results (after running `pulumi preview`).
     */
    outputFile?: string;
}

/**
 * A collection of values returned by getEnvPodMonitors.
 */
export interface GetEnvPodMonitorsResult {
    /**
     * The environment ID.
     */
    readonly environmentId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly ids: string[];
    /**
     * A list of ARMS Env Pod Monitors. Each element contains the following attributes:
     */
    readonly monitors: outputs.arms.GetEnvPodMonitorsMonitor[];
    readonly nameRegex?: string;
    /**
     * A list of ARMS Env Pod Monitor names.
     */
    readonly names: string[];
    readonly outputFile?: string;
}
/**
 * This data source provides the ARMS Env Pod Monitors of the current Alibaba Cloud user.
 *
 * > **NOTE:** Available since v1.258.0.
 */
export function getEnvPodMonitorsOutput(args: GetEnvPodMonitorsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetEnvPodMonitorsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("alicloud:arms/getEnvPodMonitors:getEnvPodMonitors", {
        "environmentId": args.environmentId,
        "ids": args.ids,
        "nameRegex": args.nameRegex,
        "outputFile": args.outputFile,
    }, opts);
}

/**
 * A collection of arguments for invoking getEnvPodMonitors.
 */
export interface GetEnvPodMonitorsOutputArgs {
    /**
     * The environment ID.
     */
    environmentId: pulumi.Input<string>;
    /**
     * A list of ARMS Env Pod Monitor IDs.
     */
    ids?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A regex string to filter results by ARMS Env Pod Monitor name.
     */
    nameRegex?: pulumi.Input<string>;
    /**
     * File name where to save data source results (after running `pulumi preview`).
     */
    outputFile?: pulumi.Input<string>;
}
