// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * This data source provides the ARMS Env Features of the current Alibaba Cloud user.
 *
 * > **NOTE:** Available since v1.258.0.
 */
export function getEnvFeatures(args: GetEnvFeaturesArgs, opts?: pulumi.InvokeOptions): Promise<GetEnvFeaturesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("alicloud:arms/getEnvFeatures:getEnvFeatures", {
        "environmentId": args.environmentId,
        "ids": args.ids,
        "nameRegex": args.nameRegex,
        "outputFile": args.outputFile,
    }, opts);
}

/**
 * A collection of arguments for invoking getEnvFeatures.
 */
export interface GetEnvFeaturesArgs {
    /**
     * The ID of the environment instance.
     */
    environmentId: string;
    /**
     * A list of ARMS Env Feature IDs.
     */
    ids?: string[];
    /**
     * A regex string to filter results by ARMS Env Feature name.
     */
    nameRegex?: string;
    /**
     * File name where to save data source results (after running `pulumi preview`).
     */
    outputFile?: string;
}

/**
 * A collection of values returned by getEnvFeatures.
 */
export interface GetEnvFeaturesResult {
    /**
     * The ID of the environment instance.
     */
    readonly environmentId: string;
    /**
     * A list of ARMS Env Features. Each element contains the following attributes:
     */
    readonly features: outputs.arms.GetEnvFeaturesFeature[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly ids: string[];
    readonly nameRegex?: string;
    /**
     * A list of ARMS Env Feature names.
     */
    readonly names: string[];
    readonly outputFile?: string;
}
/**
 * This data source provides the ARMS Env Features of the current Alibaba Cloud user.
 *
 * > **NOTE:** Available since v1.258.0.
 */
export function getEnvFeaturesOutput(args: GetEnvFeaturesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetEnvFeaturesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("alicloud:arms/getEnvFeatures:getEnvFeatures", {
        "environmentId": args.environmentId,
        "ids": args.ids,
        "nameRegex": args.nameRegex,
        "outputFile": args.outputFile,
    }, opts);
}

/**
 * A collection of arguments for invoking getEnvFeatures.
 */
export interface GetEnvFeaturesOutputArgs {
    /**
     * The ID of the environment instance.
     */
    environmentId: pulumi.Input<string>;
    /**
     * A list of ARMS Env Feature IDs.
     */
    ids?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A regex string to filter results by ARMS Env Feature name.
     */
    nameRegex?: pulumi.Input<string>;
    /**
     * File name where to save data source results (after running `pulumi preview`).
     */
    outputFile?: pulumi.Input<string>;
}
