// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * This data source provides the ARMS Env Service Monitors of the current Alibaba Cloud user.
 *
 * > **NOTE:** Available since v1.258.0.
 */
export function getEnvServiceMonitors(args: GetEnvServiceMonitorsArgs, opts?: pulumi.InvokeOptions): Promise<GetEnvServiceMonitorsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("alicloud:arms/getEnvServiceMonitors:getEnvServiceMonitors", {
        "environmentId": args.environmentId,
        "ids": args.ids,
        "nameRegex": args.nameRegex,
        "outputFile": args.outputFile,
    }, opts);
}

/**
 * A collection of arguments for invoking getEnvServiceMonitors.
 */
export interface GetEnvServiceMonitorsArgs {
    /**
     * The environment ID.
     */
    environmentId: string;
    /**
     * A list of ARMS Env Service Monitor IDs.
     */
    ids?: string[];
    /**
     * A regex string to filter results by ARMS Env Service Monitor name.
     */
    nameRegex?: string;
    /**
     * File name where to save data source results (after running `pulumi preview`).
     */
    outputFile?: string;
}

/**
 * A collection of values returned by getEnvServiceMonitors.
 */
export interface GetEnvServiceMonitorsResult {
    /**
     * The environment ID.
     */
    readonly environmentId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly ids: string[];
    /**
     * A list of ARMS Env Service Monitors. Each element contains the following attributes:
     */
    readonly monitors: outputs.arms.GetEnvServiceMonitorsMonitor[];
    readonly nameRegex?: string;
    /**
     * A list of ARMS Env Service Monitor names.
     */
    readonly names: string[];
    readonly outputFile?: string;
}
/**
 * This data source provides the ARMS Env Service Monitors of the current Alibaba Cloud user.
 *
 * > **NOTE:** Available since v1.258.0.
 */
export function getEnvServiceMonitorsOutput(args: GetEnvServiceMonitorsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetEnvServiceMonitorsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("alicloud:arms/getEnvServiceMonitors:getEnvServiceMonitors", {
        "environmentId": args.environmentId,
        "ids": args.ids,
        "nameRegex": args.nameRegex,
        "outputFile": args.outputFile,
    }, opts);
}

/**
 * A collection of arguments for invoking getEnvServiceMonitors.
 */
export interface GetEnvServiceMonitorsOutputArgs {
    /**
     * The environment ID.
     */
    environmentId: pulumi.Input<string>;
    /**
     * A list of ARMS Env Service Monitor IDs.
     */
    ids?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A regex string to filter results by ARMS Env Service Monitor name.
     */
    nameRegex?: pulumi.Input<string>;
    /**
     * File name where to save data source results (after running `pulumi preview`).
     */
    outputFile?: pulumi.Input<string>;
}
